### PR TITLE
fix(expect): align `toEqual` to jest

### PR DESCRIPTION
**Pull request by eryue0220**
This pr is to solve #4244

### CODE REVIEW

**Comment by kt3k** [comment]
Thanks for trying this, but this is significant breaking change to `assertEquals` and we can't merge this.

Fundamental issue here is that we share the same logic for `assertEquals` and `expect().toEqual()` but they have many incompatibilities in edge cases.

I think it's time to fork `assertEquals` for `std/expect` to safely diverge these 2 different APIs. Can you copy the necessary part of `assertEquals` under `expect/` as internal utilities and apply these change to them?

**Comment by eryue0220** [comment]
> Thanks for trying this, but this is significant breaking change to `assertEquals` and we can't merge this.
> 
> Fundamental issue here is that we share the same logic for `assertEquals` and `expect().toEqual()` but they have many incompatibilities in edge cases.
> 
> I think it's time to fork `assertEquals` for `std/expect` to safely diverge these 2 different APIs. Can you copy the necessary part of `assertEquals` under `expect/` as internal utilities and apply these change to them?

Sure, I'll update this.

**Comment by eryue0220** [comment]
I‘ve update the `std/expect`, which will refers to `toEqual` and `toStrictEqual`. Besides fix the issues #4244 cases, this pr also align some other cases to jest.

**Comment by kt3k** [comment]
Looks great! Thanks for these changes.

I'd like to point one another thing. The below doesn't pass in Jest, but it passes with this change.
```js
class A {}
class B {}
expect(new A()).toStrictEqual(new B());
```

I think we need to add constructor check if `strictCheck` is true.

**Comment by eryue0220** [comment]
> Looks great! Thanks for these changes.
> 
> I'd like to point one another thing. The below doesn't pass in Jest, but it passes with this change.
> 
> ```js
> class A {}
> class B {}
> expect(new A()).toStrictEqual(new B());
> ```
> 
> I think we need to add constructor() check if `strictCheck` is true.

Thank you,

I've fixed this problem.

**Review by kt3k — APPROVED** [review]
LGTM. This looks great improvements towards jest compatibility. Thanks for working on this!

**Pull request merged**
