### PR TITLE
fix(io): simplify deprecated exports

### PR DESCRIPTION
**Pull request by iuioiua**
This change simplifies the deprecated exports introduced in #2975. They were needlessly convoluted and, in hindsight, a silly approach. This also hopefully fixes the issues in https://github.com/denoland/deno/pull/16881.

### CODE REVIEW

**Comment by lino-levan** [comment]
LGTM

**Comment by lino-levan** [comment]
Wait hold on, does the deprecation message propagate to the exports properly?

**Comment by iuioiua** [comment]
No, that’s why I drafted it 🥲

I’ll get to this as soon as I can.

**Comment by iuioiua** [comment]
Closing n favour of #3056.

**Pull request closed without merging**
