### PR TITLE
fix(node/http): improve http.Server#close() compat

### PR DESCRIPTION
**Pull request by bnoordhuis**
Test fails like this:
```
running 2 tests from file:///home/bnoordhuis/src/std/node/http_test.ts
test [node/http listen] ... ok (9ms)
test [node/http chunked response ... FAILED (12ms)

failures:

[node/http chunked response
AssertionError: Test case is leaking async ops.
Before:
  - dispatched: 9
  - completed: 9
After:
  - dispatched: 18
  - completed: 17
Ops:
  op_http_accept:
    Before:
      - dispatched: 0
      - completed: 0
    After:
      - dispatched: 2
      - completed: 1

Make sure to await all promises returned from Deno APIs before
finishing test case.
    at assert (deno:runtime/js/06_util.js:41:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:96:7)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:112:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:144:9)
    at async runTest (deno:runtime/js/40_testing.js:349:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:460:22)

failures:

        [node/http chunked response

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (132ms)
```
I think it's because `server.close()` doesn't terminate the loop in `#listenLoop()` but I don't know how to fix that. Suggestions welcome.

### CODE REVIEW

**Comment by lucacasonato** [comment]
> I think it's because server.close() doesn't terminate the loop in #listenLoop() but I don't know how to fix that.

The inner loops or the outer loop/

**Comment by lucacasonato** [comment]
The loop outer loop should terminate after the next round of the event loop. What if you `this.emit("close");` after the `for await` loop?

**Comment by bnoordhuis** [comment]
@lucacasonato Doesn't change anything. Neither does moving `promise.resolve()` to a `"close"` event listener afterwards (not that that would be a good solution.)

**Comment by kt3k** [comment]
`op_http_accept` seems dispatched twice but only completed once. I don't have no idea how to complete the 2nd op call though..

**Comment by kt3k** [comment]
It seems that we need to keep track of `HttpConn`s from `Deno.serveHttp(conn)` and close those as well when the server closing as `std/http/server` does. ref: https://github.com/denoland/deno_std/blob/b4b4314c71feb3de4275e8bd5663c7caae511225/http/server.ts#L319-L321

Maybe the easier way to implement it is to use `std/http/server` in `node/http`

**Comment by bnoordhuis** [comment]
@kt3k Tracking and manually closing connections sounds reasonable but it doesn't make the op_http_accept error go away, presumably because that's the server, not the client.

**Comment by bnoordhuis** [comment]
Okay, I figured it out. This PR is now a http.Server#close() compat fix, PTAL. I'll tackle the chunked response bug in another PR.

**Review by lucacasonato — APPROVED** [review]

**Pull request merged**
