### PR TITLE
refactor(assert,internal): rename `diffstr()` to `diffStr()`

### PR DESCRIPTION
**Pull request by iuioiua**
There's no reason for this function to not adhere to the function naming convention.

Prerequisite #4757

### CODE REVIEW

**Comment by kt3k** [comment]
`@std/assert@0.225.2` will be broken by this change.

**Comment by iuioiua** [comment]
How?

**Comment by kt3k** [comment]
`@std/assert@0.225.2` depends on `@std/internal@^0.225.1`. The dependency automatically upgrades to the next version of `@std/internal`, but it still imports `diffstr` and that import doesn't work

**Comment by iuioiua** [comment]
But won't both packages be upgraded at the same time?

**Comment by kt3k** [comment]
The next version of `@std/assert` will work with the next version of `@std/internal`, but we can't modify `@std/assert@0.225.2` at this point, and it still depends on the future (patch-upgraded) version of `@std/internal`

**Comment by kt3k** [comment]
I think the solution would be upgrading `@std/internal` version (probably major?) in this PR or another PR.

**Comment by iuioiua** [comment]
Ok. I can upgrade it in a follow-up PR.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
