### PR TITLE
BREAKING(collections): remove `groupBy()`

### PR DESCRIPTION
**Pull request by iuioiua**
To be merged for v0.211.0.

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by av** [comment]
This change made me greatly confused while exploring `@std/collections`.

`groupBy` is the main reason why I'm reaching out to lodash-like libraries, so not being able to find it at first, and then having to discover it was removed (without a trace of explanation) was a bit frustrating.

**Comment by iuioiua** [comment]
Apologies, @av. Yes, we should've included relevant info. `groupBy()` was replaced by the JS-native [`Object.groupBy()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy).

**Comment by av** [comment]
Thanks for getting back to me. I figured it out, just wanted to leave some feedback for the team. Thank you!

**Pull request merged**
