### PR TITLE
Remove std/node, it was merged into Deno itself

### PR DESCRIPTION
**Pull request by ry**
Ref https://github.com/denoland/deno/pull/17785 https://github.com/denoland/deno/pull/17777

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by iuioiua** [comment]
These LOC can be removed or modified:
https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/.gitattributes#L4-L6
https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/_tools/check_assertions.ts#L10
https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/_tools/check_assertions.ts#L10-L33
https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/_tools/check_deprecation.ts#L12
https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/_tools/check_doc_imports.ts#L18
https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/_tools/check_licence.ts#L7-L13
https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/_tools/release/02_create_pr.ts#L42
https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/crypto/_wasm/README.md?plain=1#L1-L3
https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/README.md?plain=1#L91-L104

These whole files can be deleted:
* https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/_util/download_file.ts
* https://github.com/denoland/deno_std/blob/4766e411f160da1e2f32877126eca3435c85f6cf/_util/download_file_test.ts

**Comment by kt3k** [comment]
@iuioiua Thanks for your review! Addressed your comments

**Comment by iuioiua** [comment]
LGTM now!

**Pull request merged**
