### PR TITLE
chore: update `check_circular_package_dependencies.ts` for workspaces

### PR DESCRIPTION
**Pull request by kt3k**
`_tools/check_circular_package_dependencies.ts` was disabled in #4650 

This PR re-enables it.

related #4544 #4600

### CODE REVIEW

**Comment by iuioiua** [comment]
I tested this locally by creating a two-way dependency between `@std/fs/copy` and `@std/path/basename` and got `Circular dependencies found: fs -> path -> fs`, which doesn't provide sufficient troubleshooting detail. Can we improve this a little?

**Comment by kt3k** [comment]
What information would you suggest to add?

**Comment by iuioiua** [comment]
Just a bit more specificity, such as the exact modules in question. E.g.
```
Circular dependencies found: fs/copy -> path/basename -> fs/copy
```

**Comment by kt3k** [comment]
Sounds a good idea, but that requires fair amount of work. Sounds out of scope of this PR. Created a new issue https://github.com/denoland/deno_std/issues/4656

**Review by iuioiua — APPROVED** [review]

**Pull request merged**
