### PR TITLE
refactor(bytes): rename `contains` to `includes` with optional argument `fromIndex`

### PR DESCRIPTION
**Pull request by zhangyuannie**
- Rename `contains` to `includes` as discussed in std-wg.
- Add optional argument `fromIndex` to `includes` since `Array.prototype.includes` has it.

### CODE REVIEW

**Comment by kt3k** [comment]
@zhangyuannie Thank you for your contribution! Most part looks good to me.

Because `contains` existed for a relatively long time (ref https://github.com/denoland/deno/pull/4801), I think it would be safer to add an alias to it with `@deprecated` annotation like:

```
/** @deprecated */
export { includes as contains };
```

**Comment by zhangyuannie** [comment]
> @zhangyuannie Thank you for your contribution! Most part looks good to me.
> 
> Because `contains` existed for a relatively long time (ref [denoland/deno#4801](https://github.com/denoland/deno/pull/4801)), I think it would be safer to add an alias to it with `@deprecated` annotation like:
> 
> ```
> /** @deprecated */
> export { includes as contains };
> ```

Sounds good!

**Review by kt3k — APPROVED** [review]
@zhangyuannie LGTM. Thanks!

**Comment by kt3k** [comment]
For future reference, this change is derived from std-wg on 3 Dec 2020 https://github.com/denoland/deno_std/discussions/699#discussioncomment-231367

**Pull request merged**
