### PR TITLE
feat(file_server): Print version

### PR DESCRIPTION
**Pull request by zhmushan**
When I use File Server again after a long time, I often want to know which version I'm on.

### CODE REVIEW

**Comment by kt3k** [comment]
I'm fine with this change. Is there any concerns/objections to this?

**Comment by lino-levan** [comment]
This makes a lot of sense.

LGTM

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
@zhmushan Thanks for your contribution!

**Pull request merged**
