### PR TITLE
Remove fs/mod.ts

### PR DESCRIPTION
**Pull request by ry**
Fixes https://github.com/denoland/deno_std/issues/1539

### CODE REVIEW

**Comment by bartlomieju** [comment]
This will break an enormous amount of code in the wild and doesn't solve the issue of requiring unstable at all. We should at least deprecate this module for a few release before removing completely.

**Comment by ry** [comment]
We make breaking changes in std often. I would just remove this...

**Comment by LionC** [comment]
> We make breaking changes in std often. I would just remove this...

@ry does that mean that you plan to cover even more abstract FS related cases (e.g. `walk`) in the runtime API in the future? Or do you propose to straight up not cover them at all?

**Comment by bartlomieju** [comment]
> We make breaking changes in std often. I would just remove this...

I'm still not in favor of this change. This make it more cumbersome for users to import APIs (now you have to add 5 imports instead of one) without an obvious benefit. The root issues is still not resolved with this change.

**Comment by kt3k** [comment]
How about only removing `./copy.ts` from `fs/mod.ts`, which also resolves #1539 with less breaking changes.

**Comment by ry** [comment]
@kt3k Ok I've made that change.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
