### PR TITLE
refactor(assert): vendor code from `fmt/colors.ts`

### PR DESCRIPTION
**Pull request by iuioiua**
Towards #4717

### CODE REVIEW

**Comment by iuioiua** [comment]
Frankly, I'd prefer we minimize our use of colors as much as possible.

**Comment by kt3k** [comment]
Maybe this only makes sense when we reached a consensus on #4676

**Comment by iuioiua** [comment]
How does that issue affect this PR?

**Comment by kt3k** [comment]
If we don't move `fmt/colors` (and stabilize it as is), then we don't need to do this

**Comment by iuioiua** [comment]
Stabilizing `std/fmt` blocks the stabilization of `std/internal` and `std/assert`, and stabilizing `std/fmt` is not yet on the radar. I think we should proceed with this PR.

**Comment by kt3k** [comment]
Ok. Makes sense

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
