### PR TITLE
refactor: mark modules as browser compatible

### PR DESCRIPTION
**Pull request by jsejcksn**
Cont. of https://github.com/denoland/deno_std/pull/1972
Tracking ref: https://github.com/denoland/deno_std/issues/1973

### CODE REVIEW

**Comment by jsejcksn** [comment]
TS was upgraded to v`4.6.2` in Deno v`1.20.1`, and these modules should now pass the compatibility tests.

**Comment by bartlomieju** [comment]
This looks good, it seems you hit some flake in Node tests @jsejcksn. Try re-running the CI

**Comment by jsejcksn** [comment]
> This looks good, it seems you hit some flake in Node tests @jsejcksn. Try re-running the CI

@bartlomieju I re-ran, but there are still failures. I know they aren't related to my changes. Is there something wrong with the node CI actions?

**Comment by bartlomieju** [comment]
I'm not sure really. @kt3k could you take a look?

**Comment by kt3k** [comment]
Seems like the failure was caused by the outage of npm. Going to run the CI again

**Comment by jsejcksn** [comment]
@kt3k Thanks for troubleshooting

**Review by kt3k — APPROVED** [review]
Now LGTM. Thanks for continuing to work on this! @jsejcksn

**Pull request merged**
