### PR TITLE
BREAKING(yaml): rename `StringifyOptions.noRefs` to `StringifyOptions.useAnchors`

### LINKED ISSUE #5124: yaml: Rename negative property names in options
I think some properties of function options are poorly named. Options should be formulated positively imo and the default value adjusted accordingly.

https://github.com/denoland/deno_std/blob/3fac8a2e8655150181835acf83fd8a9071d5cd0e/yaml/_dumper/dumper_state.ts#L45
Proposal: Rename to `indentArrays` or something similar.

https://github.com/denoland/deno_std/blob/3fac8a2e8655150181835acf83fd8a9071d5cd0e/yaml/_dumper/dumper_state.ts#L74
The comment states: `if true, don't convert duplicate objects into references (default: false)`. Is it just me or is this confusing?
Proposal: Rename to `createRefs` or something similar.

https://github.com/denoland/deno_std/blob/3fac8a2e8655150181835acf83fd8a9071d5cd0e/yaml/_dumper/dumper_state.ts#L80
Proposal: Rename to `compatMode` or something similar.

WDYT?

### PR DESCRIPTION
**Pull request by iuioiua**
### What's changed

The `ParseOptions.noRefs` option has been renamed to `ParseOptions.useAnchors`. As a result, the polarity of the option has been swapped. In other words, `true` behavior has been changed to `false` behavior, and visa-versa. This only affects users who currently use `ParseOptions.noRefs`.

### Motivation

This change makes the option far easier to understand by avoiding a negative-tensed name.

### Migration guide

Use `ParseOptions.useAnchors` instead of `ParseOptions.noRefs` and swap the polarity of the option.

```diff
import { parse } from "@std/yaml/parse";

const yamlString = `fruits:
  - Apple
  - Banana
  - Cherry`;

- parse(yamlString, { noRefs: false });
+ parse(yamlString, { useAnchors: true });
```

### Related

Closes #5124

### CODE REVIEW

**Comment by kt3k** [comment]
I tested `noRefs` option, but it doesn't seem working in `std/yaml`.

```ts
import { stringify } from "./yaml/mod.ts";
import * as yaml from "npm:js-yaml";

const b = { baz: 42 };
const a = {
  foo: {
    foo: {
      foo: {
      },
    },
  },
};
console.log(stringify([a, a], { noRefs: false }));
console.log(stringify([a, a], { noRefs: true }));
console.log(yaml.dump([a, a], { noRefs: false }));
console.log(yaml.dump([a, a], { noRefs: true }));
```

This prints:
```
- foo:
    foo:
      foo: {}
- foo:
    foo:
      foo: {}

- foo:
    foo:
      foo: {}
- foo:
    foo:
      foo: {}

- &ref_0
  foo:
    foo:
      foo: {}
- *ref_0

- foo:
    foo:
      foo: {}
- foo:
    foo:
      foo: {}
```

I suggest we should rather remove this option. What do you think?

**Comment by iuioiua** [comment]
Oh, yes, let's remove then.

**Comment by kt3k** [comment]
Ah, wait. The feature seems working with 0.224.3, but it's gone in 1.0.0-rc.1. It seems broken somewhere between 0.224.3 - 1.0.0-rc.1

**Comment by kt3k** [comment]
How about `useAnchors` instead? 'reference' is not an official yaml term for it. Also 'create' sounds a bit strange to me. It reduces the duplicate occurrence of the same objects, instead of creating something

**Comment by iuioiua** [comment]
SGTM

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
