### PR TITLE
node: add FreeBSD support

### PR DESCRIPTION
**Pull request by unrelentingtech**
This adds enough support for node compat to run on FreeBSD (which [has Deno packaged](https://www.freshports.org/www/deno), despite not being an official platform).

### CODE REVIEW

**Comment by cjihrig** [comment]
The CI is failing because "freebsd" is not a valid value for `Deno.build.os`. There is an open issue for that in the core repo: https://github.com/denoland/deno/issues/14799

**Comment by kt3k** [comment]
I'm open to doing type casting in `switch (Deno.build.os)`

**Comment by cjihrig** [comment]
@unrelentingtech are you still interested in pursuing this? If so, please see the previous comment.

**Comment by unrelentingtech** [comment]
yes, I'll try that, sure

**Review by cjihrig — APPROVED** [review]
LGTM. The CI failures are not related to the changes here.

**Pull request merged**
