### PR TITLE
Fixes HTTP module when no body is sent.

### LINKED ISSUE #538: [HTTP] Body's Promise is blocked when no body is present
- Code to replicate:

```ts
import { serve } from "https://deno.land/std@v0.11.0/http/server.ts";
const s = serve("0.0.0.0:8000");

async function main() {
  for await (const req of s) {
    const body = await req.body()
    console.log('Request body:', body)
    req.respond({ body: new TextEncoder().encode("Hello World\n") });
  }
}

main();
```
- Send GET: http://127.0.0.1:8000/ OK

image

- Send POST (with some body): http://127.0.0.1:8000/ OK

image

- Send POST (without body): http://127.0.0.1:8000/ BLOCKS

image

### PR DESCRIPTION
**Pull request by ConsoleTVs**
- Fixes #538

### CODE REVIEW

**Comment by ry** [comment]
Is it possible to add a test that demos this problem so we don't regress in the future?

**Comment by ConsoleTVs** [comment]
> Is it possible to add a test that demos this problem so we don't regress in the future?

Yes it is. I'm on it right now.

**Comment by ConsoleTVs** [comment]
@ry I added the tests, but to me those tests are not really reliable since I've tried some of yours (by changing for instance, the content length to 0 and sending something in the body and worked with your current branch). However, I followed the same format. Removed the buffer contents, added content length to 0 and asserted to "".

**Comment by ry** [comment]
@ConsoleTVs Hm, we need a test where it fails before the change but is fixed after. I will take a look later if you haven't got it already.

BTW the CI is red due to formatting, run `deno fmt http` to fix.

**Comment by bartlomieju** [comment]
@ConsoleTVs any update on this PR?

**Comment by ConsoleTVs** [comment]
Hello @bartlomieju I currently have no time to add the test. Can you provide one please?

That's how I currently avoid this issue: https://github.com/arkoren/framework/blob/master/app.ts#L139

**Comment by M4rk9696** [comment]
@ConsoleTVs I've raised a PR against your branch with the test

**Pull request closed without merging**
