### PR TITLE
fix(io): readDelim returns wrong result if delim strides over chunks

### PR DESCRIPTION
**Pull request by keroxp**
- This is bug from #867 
- @ry Sorry, would you see this?

### CODE REVIEW

**Comment by kfdf** [comment]
Nice to see the issue #803 is being handled, but as I mentiond before, the `createLPS` function is still bugged. This causes an infinite loop:
```
import { readStringDelim } from 'https://deno.land/std@0.95.0/io/mod.ts'
readStringDelim(null, '1213').next()
```
As may the use of very long delimiters (longer than 256 bytes).

**Comment by keroxp** [comment]
@kfdf Oh, that's true! Also fixed on 82b327a

**Comment by kfdf** [comment]
Wait, maybe I'm missing something, because the previous PR was benchmarked, but this doesn't actually fix #803?
```
import { readLines, StringReader } from 'https://deno.land/std@0.95.0/io/mod.ts'
let reader = new StringReader('X'.repeat(10_000_000))
for await (let _ of readLines(reader)) ;
```
This takes about 1.5 minutes for me, and the time grows quadraticaly with size.

**Review by kt3k — APPROVED** [review]
@keroxp Thank you for the fix! LGTM

@kfdf Thank you for your review!

**Pull request merged**
