### PR TITLE
chore: release 2024.05.29

### PR DESCRIPTION
**Pull request by denobot**
The following updates are detected:

| module   | from    | to      | type  |
|----------|---------|---------|-------|
|cli|0.224.3|0.224.4|patch|
|data-structures|0.224.1|0.225.0|minor|
|encoding|0.224.2|0.224.3|patch|
|expect|0.224.2|0.224.3|patch|
|fmt|0.225.1|0.225.2|patch|
|front-matter|0.224.0|0.224.1|patch|
|html|0.224.0|0.224.1|patch|
|http|0.224.1|0.224.2|patch|
|ini|0.224.0|0.225.0|minor|
|msgpack|0.224.1|0.224.2|patch|
|semver|0.224.0|0.224.1|patch|
|streams|0.224.1|0.224.2|patch|
|text|0.224.0|0.224.1|patch|
|ulid|0.224.0|0.224.1|patch|
|uuid|0.224.2|0.224.3|patch|
|yaml|0.224.0|0.224.1|patch|

Please ensure:
- [x] Versions in deno.json files are updated correctly
- [x] Releases.md is updated correctly

The following commits are ignored:

- [chore: update dependency graph (#4881)](/denoland/deno_std/commit/7717c291738b79b116700b41135874f93c5787d5)
- [chore: don't require `@returns` tag when return type is type assertion (#4873)](/denoland/deno_std/commit/1e194f746bb3b331fd5f395c308b596021a4d0ee)
- [chore: show the total number of doc errors (#4871)](/denoland/deno_std/commit/0b95598ec109a35f679b78cd92eb9573aa34ad27)
- [chore: draw only direct dependencies in dep diagram (#4870)](/denoland/deno_std/commit/655ff100860509b6b08e00e46622ccfada1768b1)
- [chore: generate dependency graph image (#4869)](/denoland/deno_std/commit/bce7d8e38b72bacca06c33d9b6c4a19e1c25bc68)
- [chore: implement custom resolver for `doc()` (#4866)](/denoland/deno_std/commit/ab6d747f9cc5d8cec89fd4aaaa75e577e0256270)
- [chore: reorder check-doc entries (#4857)](/denoland/deno_std/commit/b9dbcb774dc2d703dca6b042e9d42c9e89586c74)
- [chore: update dependency check tool (#4833)](/denoland/deno_std/commit/082107bd7fdb9a74d30bc6eabf9777673ffcb6c4)
- [chore: suggest "Usage" as example title for documentation (#4841)](/denoland/deno_std/commit/2785a7308a6e06836c3f9326c6942d762c4ae9a7)
- [chore: update circular package check for `encoding/mod.ts` (#4824)](/denoland/deno_std/commit/acd380f7f92a9ecaa92f23d1fc5677705983a847)
- [chore: improve check_docs.ts (#4834)](/denoland/deno_std/commit/d7424a22780610c1e1e510683d86b1d61dc5f35d)

---

To make edits to this PR:

```sh
git fetch upstream release-2024-05-29-09-47-10 && git checkout -b release-2024-05-29-09-47-10 upstream/release-2024-05-29-09-47-10
```

### CODE REVIEW

**Review by kt3k — APPROVED** [review]

**Comment by kt3k** [comment]
> I feel like the following might've justified having a @std/uuid@0.224.3 release:

What do you mean? `@std/uuid@0.224.3` has been released in this release

**Comment by iuioiua** [comment]
Sorry, I mean't 0.225.0z

**Comment by kt3k** [comment]
This is intentional because `deprecation` doesn't break things unlike `BREAKING`

**Comment by iuioiua** [comment]
Is it fine to include deprecations and breaking fixes in patch releases?

**Comment by kt3k** [comment]
deprecation is fine because it basically only changes docs (the user get 'deprecated' message, but the code itself doesn't break)

> breaking fixes

I don't think 'breaking fix' is an official term (at least there's no commit tag expressing it).

**Comment by iuioiua** [comment]
Ok. The reason for including deprecations makes sense.

Your reasoning for including breaking fixes doesn't make sense to me. But on second thought, including them in a patch release is fine because they only break incorrect use of the API, which seems fine to do in a patch release.

**Pull request merged**
