### PR TITLE
deprecation(semver): deprecate `Comparator.semver` property

### PR DESCRIPTION
**Pull request by timreichen**
- deprecates `Comparator.semver` property in favour of `Comparator`extending `SemVer`.

### CODE REVIEW

**Comment by iuioiua** [comment]
What is the reasoning behind this?

**Comment by timreichen** [comment]
> What is the reasoning behind this?

Imo separating `Operator` and `SemVer` by individual properties is just unnecessary nesting.

**Comment by iuioiua** [comment]
I'm not sure about this change. It'd require many changes to the `std/semver` API, and its benefits aren't apparent.

**Comment by timreichen** [comment]
> I'm not sure about this change. It'd require many changes to the `std/semver` API, and its benefits aren't apparent.

I think it declutters the interface and. It also will simplify `SemVerRange`, and once we make `SemVerRange` redefine `SemVerRange` without the `ranges` property, it will look much more clean:

before:
```ts
const range = { ranges: [ [ { operator: "<", semver: { major: 1, minor: 2, patch: 3 } } ] ] }
```
after
```ts
const range = [ [ { operator: "<", major: 1, minor: 2, patch: 3 } ] ]
```
But we can wait with this until we decide about https://github.com/denoland/deno_std/issues/4047 and discuss this some more.

**Comment by iuioiua** [comment]
> But we can wait with this until we decide about #4047 and discuss this some more.

Yeah, I think we should do that.

**Comment by kt3k** [comment]
I think we should first decide on what to do about #4047 before changing anything about Comparator

**Comment by timreichen** [comment]
> I think we should first decide on what to do about #4047 before changing anything about Comparator

This is about the type `Comparator` which will stay public either way because it is part of `SemVerRange`.

**Comment by kt3k** [comment]
> This is about the type Comparator which will stay public either way because it is part of SemVerRange.

I think we can stop using `Comparator` in `SemVerRange` definition if we only want to change `SemVerRange`

**Comment by timreichen** [comment]
> > This is about the type Comparator which will stay public either way because it is part of SemVerRange.
> 
> I think we can stop using `Comparator` in `SemVerRange` definition if we only want to change `SemVerRange`

What do you mean exactly?

**Comment by kt3k** [comment]
For example, by replacing `Comparator` in `SemVerRangeAnd` like the below:

```ts
type SemVerRangeAnd = (SemVer & { operator: Operator })[];
```

**Comment by iuioiua** [comment]
Does this PR still apply if `Comparator` is now deprecated?

**Comment by timreichen** [comment]
> Does this PR still apply if `Comparator` is now deprecated?

I will push another PR where we can do that step when renaming `SemVerRange` to `Range` directly. Closing.

**Pull request closed without merging**
