### PR TITLE
[http] fix writeResponseBody and related issues

### PR DESCRIPTION
**Pull request by arcatdmz**
This pull request is relevant to the core bug denoland/deno#2330 present as of v0.4.0.

1. Because of the core bug, [writeResponse() in server.ts](https://github.com/denoland/deno_std/commit/dacd67eae372b26dbeff2224e9c9fa3bcd4f567b#diff-58b0092e6441ae4b79fb3069e2ba21ddR295) writes a blank response body when a `StringReader` instance is provided as `Response.body`.
  - To reproduce the issue, test cases are added in dacd67e.
  - To fix the issue, the core `toAsyncIterator` is replaced with the updated implementation in 
f525a53, which is noted as "Temporary fix."
2. With the updated `toAsyncIterator`, [responseWrite](https://github.com/denoland/deno_std/blob/dacd67eae372b26dbeff2224e9c9fa3bcd4f567b/http/server_test.ts#L70) starts to fail because a 0-byte chunk is emitted.
  - This is fixed in 74e261d, preventing 0-byte chunks from being emitted.

Once the Deno core issue with `toAsyncIterator` is fixed, I plan to submit another pull request that removes the redundant `toAsyncIterator` definition.

Meanwhile, until the next core gets shipped, this pull request should fix the whole issue.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@arcatdmz https://github.com/denoland/deno/pull/2335 has landed, so you can safely use it again.

**Comment by arcatdmz** [comment]
@bartlomieju Thanks! Though that fix is for Deno core, and it comes to the user's environment only when the user downloads the new version of Deno, doesn't it?

**Comment by bartlomieju** [comment]
It does, but latest release of standard library is compatible with Deno v0.4.0. Running master branch of std may require latest upstream version of Deno

**Comment by arcatdmz** [comment]
@bartlomieju Makes sense! so I've deleted inhouse `toAsyncIterator` and update `server.ts` to use the native one. Tests above are using Deno v0.4.0 through the following code and thus are failing.

```sh
curl -L https://deno.land/x/install/install.sh | sh -s v0.4.0
```

Shall I send a pull request to use the latest v0.5.0 for tests in `azure-pipelines.yml`?

https://github.com/denoland/deno_std/blob/master/azure-pipelines.yml#L2

**Comment by bartlomieju** [comment]
@arcatdmz just wait for #393 to land

**Comment by ry** [comment]
Thanks @arcatdmz and sorry for the delay.  I'm landing this one in https://github.com/denoland/deno_std/pull/393

**Pull request closed without merging**
