### PR TITLE
feat(collections): add takeWhile

### PR DESCRIPTION
**Pull request by grian32**
I've currently made the array return a empty array if the collection given is an empty array, not sure that's the best approach.

Ref: #1173

### CODE REVIEW

**Comment by grian32** [comment]
I've optimized this function based on a discussion in discord(read down from here: https://discord.com/channels/684898665143206084/775393009981849600/881533625491947541), credit to @evanwashere for the new implementation.

I'd like also like to bring up re-naming it to `takeWhile`, as that is what rust, the iterator-helpers proposal and kotlin(which this was based off of) uses.

**Comment by LionC** [comment]
I like `takeWhile`. I can't remember which discussion lead to naming it `takeFirstWhile` in the proposal, but I definitely prefer `takeWhile`

**Review by LionC — APPROVED** [review]
This looks good to me now, pinging @kt3k

**Review by kt3k — APPROVED** [review]
@grian32 Thanks! LGTM

**Pull request merged**
