### PR TITLE
[WIP] feat: net.Socket

### PR DESCRIPTION
**Pull request by ebebbington**
Partially addresses https://github.com/denoland/deno_std/issues/666

Moved from `https://github.com/denoland/deno`, see [here](https://github.com/denoland/deno/pull/8949) for original PR

- [ ] Tests
- [x] All code required copied over
- [ ] Port bindings
- [x] Port requires
- [ ] Port primordials
- [ ] Port JS to TS (largely relies on bindings)

### CODE REVIEW

**Comment by ebebbington** [comment]
Regarding the latest comments in the original PR, myself and @bartlomieju discussed a few bits on discord:

image
image
image
image

**Comment by ebebbington** [comment]
@bartlomieju How would i go about "emulating" some of the internal bindings? Is it just a matter of finding the source code and converting it from c++ into typescript?

**Comment by bartlomieju** [comment]
> @bartlomieju How would i go about "emulating" some of the internal bindings? Is it just a matter of finding the source code and converting it from c++ into typescript?

@ebebbington yes, pretty much

**Comment by ebebbington** [comment]
I believe there's only 1 `require` statement i need to address, and the rest is porting bindings and adding types

**Comment by ebebbington** [comment]
Stopping work on this PR for the time being, until either bindings are implemented (im unable to do them unfortunately) or when https://github.com/denoland/deno_std/pull/695 is merged (then ill get the tests sorted)

**Comment by jopemachine** [comment]
As far as I know, Deno uses tokio instead of libuv to handle Async I/O. 

Is it possible to emulate these internal bindings (c++ code like `tcp_wrap.cc`) without libuv?

Should it be implemented through tokio?

**Comment by ry** [comment]
@ebebbington Thanks for the work on this patch - I'm going to close it tho because it's stale and not close to being mergeable. We very much would like to support std/node/net so hopefully we can come back and reference this patch when someone attempts to undertake it.

**Comment by ebebbington** [comment]
> @ebebbington Thanks for the work on this patch - I'm going to close it tho because it's stale and not close to being mergeable. We very much would like to support std/node/net so hopefully we can come back and reference this patch when someone attempts to undertake it.

Fair enough :) unfortunately I probably won’t have enough time in the future to carry on with it so best of luck to whoever may wish to take it on in the future!

**Pull request closed without merging**
