### PR TITLE
revert(collection): Remove findLastIndex from `std/collections`

### PR DESCRIPTION
**Pull request by getspooky**
Related https://github.com/denoland/deno_std/issues/1525

### CODE REVIEW

**Comment by kt3k** [comment]
Let's land this for Deno 1.17.0 (std 0.117.0 or 0.118.0)

**Comment by getspooky** [comment]
@kt3k any update ?

**Comment by kt3k** [comment]
@getspooky 
We're going to release Deno 1.17 next week. ref: https://deno.land/manual@v1.16.4/contributing/release_schedule

We'll merge this PR right before that time (probably some time after the next Friday). We'd appreciate if you could resolve the conflict with main branch

**Comment by getspooky** [comment]
@kt3k fixed.

**Review by kt3k — APPROVED** [review]

**Review by bartlomieju — APPROVED** [review]

**Comment by bartlomieju** [comment]
@getspooky please resolve conflicts, as I can't push to your branch.

**Pull request merged**
