### PR TITLE
feat(testing): Add assertIsError

### PR DESCRIPTION
**Pull request by KyleJune**
Closes https://github.com/denoland/deno_std/issues/1182

The assertThrows and assertRejects functions had common code for making assertions about errors that is useful on its own. This change moves the shared code to its own function called assertError. I updated assertThrows and assertRejects to use assertError.

### CODE REVIEW

**Comment by KyleJune** [comment]
> If we want to factor out duplicate code for maintenance purposes, this should be private (by either not exporting it or calling it `_assertError`). Having it in the public API is confusing and it's very niche.

I don't think it would be confusing or too niche. Two other people have found my issue and liked it. This saves people from having to re-throw an error to be able to use the error assertions available in assertThrows and assertRejects.

With assertError, if I've already caught the error and would like to make an assertion about it, I could do the following.

```ts
assertError(error, CustomError, "fail");
```

Without assertError, I would need to create a function and make it re-throw the error like this.

```ts
assertThrows(
  () => {
    throw error;
  },
  CustomError,
  "fail",
);
```

**Comment by nayeemrmn** [comment]
Any data structure benefits from having a specialised assertion function to check values with knowledge of the structure. We only have a utility for _thrown_ errors because that's a central case with special control flow behaviour and more boilerplate to hide. IMO the assertion utilities we have should strive to add more value than being able to express multiple expectations at once as positional arguments. This doesn't improve error messages much compared to @kt3k's example in https://github.com/denoland/deno_std/issues/1182#issuecomment-912279645.

**Comment by kt3k** [comment]
I'm in favor of this addition. Some people prefer returning errors instead of throwing them. This utility supports that style of coding better.

**Comment by wojpawlik** [comment]
:+1:, this is very useful for TypeScript, even (especially?) outside testing:

```ts
try {
  foo()
} catch (error: unknown /* default since TS 4.4 */) {
  assertError(error, Error)
  // error is now Error, not unknown 
}
```

**Pull request merged**
