### PR TITLE
feat(std/node): add `ParsedUrlQuery` to querystring

### PR DESCRIPTION
**Pull request by talentlessguy**
This PR adds the following type:

```ts
export interface ParsedUrlQuery {
  [key: string]: string | string[] | undefined;
}
```

this fixes https://github.com/alephjs/esm.sh/issues/115

### CODE REVIEW

**Comment by kt3k** [comment]
@talentlessguy Thank you for your contribution.

ParsedUrlQuery is not strictly part of node.js API, but it's defined and used in [`@types/node`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/43dc8c40f145ad0aa33e2cc91e6cd00f002bf944/types/node/querystring.d.ts) (community type definition of node.js), and [tinyhttp](https://github.com/tinyhttp/tinyhttp) uses it. That's why this change is needed. Please correct me if I'm missing something.

I'm in favor of this change, but if we introduce this type, I think we should use this type as the returned type of `parse` to follow the typing of `@types/node`

**Comment by talentlessguy** [comment]
ok I will use it as a return type for `parse`, will push the fix soon

**Comment by talentlessguy** [comment]
@kt3k I added `ParsedUrlQuery` type as a return type for `parse`, please take a look :)

**Review by kt3k — APPROVED** [review]
@talentlessguy LGTM. Thank you for your contribution!

**Comment by talentlessguy** [comment]
omg thx for merging!

**Pull request merged**
