### PR TITLE
chore: add faketime testing

### PR DESCRIPTION
**Pull request by kt3k**
This PR adds ability to run test with the specific date time. This is necessary for writing test for #1676

### CODE REVIEW

**Comment by bartlomieju** [comment]
Adding this means you won't be able to run tests locally anymore. Any idea how we could handle that gracefully?

**Comment by kt3k** [comment]
@bartlomieju 
The faketime dependent file `datetime/test_2021_12_31.ts` has a filename which isn't auto discovered by `deno test`. So you can still run `deno test` without using `faketime` (that is what `Run tests canary` step does)

`Run test with the date 2021-12-31` step runs only `datetime/test_2021_12_31.ts` using `faketime`. You need to install `faketime` to run this test, but I think this only affects `datetime` module contributors

**Comment by bartlomieju** [comment]
> @bartlomieju The faketime dependent file `datetime/test_2021_12_31.ts` has a filename which isn't auto discovered by `deno test`. So you can still run `deno test` without using `faketime` (that is what `Run tests canary` step does)
> 
> `Run test with the date 2021-12-31` step runs only `datetime/test_2021_12_31.ts` using `faketime`. You need to install `faketime` to run this test, but I think this only affects `datetime` module contributors

Okay, sounds good to me.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Pull request merged**
