### PR TITLE
docs: remove `@$STD_VERSION` references

### PR DESCRIPTION
**Pull request by iuioiua**
Including this in the import specifier seems redundant.

### CODE REVIEW

**Comment by lino-levan** [comment]
What's the upside to doing this? This will unpin all versions (and I think it will mess up `deno check`?

**Comment by iuioiua** [comment]
Perhaps a better question is, "What is the upside of including `@$STD_VERSION` in the import specifiers?" If there's no justifiable answer, there's no reason to include it. I assume it was initially included to remind devs to consider the version of the Standard Library they require. Everyone knows about module versions when importing dependencies. This doesn't need to be re-iterated in every import specifier in every JSDoc example. I doubt removing this string will cause any issues.

A newcomer might also see the `@$STD_VERSION` and wonder if it means something beyond a placeholder for the Standard Library version. I know I did.

It won't mess up `deno check`, as the `imports` field in `deno.json` was also adjusted to match.

**Comment by cknight** [comment]
"Everyone knows about module versions when importing dependencies" is a bold statement which I don't think will hold true.  Many beginners to ESM, Deno and javascript in general won't understand the concept of module pinning.  This change will move the documentation from:

```ts
import { Tar } from "https://deno.land/std@0.204.0/archive/tar.ts";
//code example using Tar
```
to
```ts
import { Tar } from "https://deno.land/std/archive/tar.ts";
//code example using Tar
```
This will encourage many people to use unpinned versions after they copy and paste the code, when module pinning is best practice.

**Comment by iuioiua** [comment]
> This will encourage many people to use unpinned versions after they copy and paste the code, when module pinning is best practice.

Actually, that might be a justifiable answer.

**Pull request closed without merging**
