### PR TITLE
fix: node:stream/web wrapper formatting, declaration order

### PR DESCRIPTION
**Pull request by guybedford**
This updates the `stream/web` wrapper to match the Node.js ESM interface wrapper and also to include declarations in the same ordering for easier auditing.

### CODE REVIEW

**Comment by lucacasonato** [comment]
Opened an issue for the typings issues here: https://github.com/denoland/deno/issues/12484

**Comment by kt3k** [comment]
The type errors are rooted from the upstream issue in TypeScript repo, and might not be solved anytime soon

I think the alternative solution here could be something like:

```js
const {
  ReadableStream: ReadableStream_,
  ...
} = { 
  ReadableStream,
  ...
};

export {
  ReadableStream_ as ReadableStream,
  ...
};

export default {
  ReadableStream: ReadableStream_
  ...
};
```

**Comment by bartlomieju** [comment]
@guybedford I covered them in https://github.com/denoland/deno/pull/12497

**Comment by bartlomieju** [comment]
@guybedford please sign the CLA

**Pull request merged**
