### PR TITLE
fix: update branch in README link

### PR DESCRIPTION
**Pull request by jsejcksn**

### CODE REVIEW

**Comment by jsejcksn** [comment]
Aside: I'm curious about the criteria for releases being included in the linked compatibility file.

e.g. [`deno_std@0.101.0`](https://github.com/denoland/deno_std/releases/tag/0.101.0) was released yesterday, but it is not presently included in the file. Is the file only updated when there are CLI releases?

**Comment by satyarohith** [comment]
> Aside: I'm curious about the criteria for releases being included in the linked compatibility file.
> 
> e.g. [`deno_std@0.101.0`](https://github.com/denoland/deno_std/releases/tag/0.101.0) was released yesterday, but it is not presently included in [the file](https://raw.githubusercontent.com/denoland/deno_website2/0a88d7f4b891557d6ba5c49f14eba205bcec3f4b/versions.json). Is the file only updated when there are CLI releases?

Yes, the file is updated after a corresponding CLI release.

**Review by satyarohith — APPROVED** [review]
LGTM. Thanks, @jacobgc! :)

**Review by kt3k — APPROVED** [review]
LGTM

> e.g. deno_std@0.101.0 was released yesterday, but it is not presently included in the file. Is the file only updated when there are CLI releases?

Yes, we usually update std version in the list after CLI release. There is `cli_to_std` section in it, which will include `"v1.12.0": "0.101.0"`

**Pull request merged**
