### PR TITLE
feat(node/dns): Implement Resolver APIs

### PR DESCRIPTION
**Pull request by cmorten**
Following on from #1375 and #2164 to bring the dns compat module closer to parity with Node:

Stubs or implementations for:

- `dns.Resolver`
- `dns.resolve()`
- `dns.resolve*()`

Outstanding APIs blocked by:

- https://github.com/denoland/deno/issues/14492
- https://github.com/denoland/deno/issues/14432

### CODE REVIEW

**Comment by cmorten** [comment]
Small progress test looks promising:

```ts
import { createRequire } from "./node/module.ts";

const require = createRequire(import.meta.url);

const dns = require("dns");

dns.resolveCname("www.github.com.", (err: Error, ret: string[]) => {
  console.log(err, ret); // null [ "github.com." ]
});
```

**Comment by cmorten** [comment]
Quick test for `dns.resolveAny()`:

```ts
import { createRequire } from "./node/module.ts";

const require = createRequire(import.meta.url);

const dns = require("dns");

dns.resolveAny("www.github.com.", (err: Error, ret: string[]) => {
  console.log(err, ret);
});
```

```console
$ deno run -A --unstable trial.ts
Check file:///Users/craigmorten/git/cmorten/deno_std/trial.ts
null [
  { type: "A", address: "140.82.121.3" },
  { type: "CNAME", value: "github.com." },
  { type: "MX", priority: 5, exchange: "alt1.aspmx.l.google.com." },
  { type: "MX", priority: 5, exchange: "alt2.aspmx.l.google.com." },
  { type: "MX", priority: 10, exchange: "alt3.aspmx.l.google.com." },
  { type: "MX", priority: 10, exchange: "alt4.aspmx.l.google.com." },
  { type: "MX", priority: 1, exchange: "aspmx.l.google.com." },
  { type: "TXT", entries: [ "apple-domain-verification=RyQhdzTl6Z6x8ZP4" ] },
  {
    type: "TXT",
    entries: [
      "atlassian-domain-verification=jjgw98AKv2aeoYFxiL/VFaoyPkn3undEssTRuMg6C/3Fp/iqhkV4HVV7WjYlVeF8"
    ]
  },
  { type: "TXT", entries: [ "docusign=087098e3-3d46-47b7-9b4e-8a23028154cd" ] },
  {
    type: "TXT",
    entries: [
      "stripe-verification=f88ef17321660a01bab1660454192e014defa29ba7b8de9633c69d6b4912217f"
    ]
  },
  {
    type: "TXT",
    entries: [
      "v=spf1 ip4:192.30.252.0/22 include:_netblocks.google.com include:_netblocks2.google.com include:_net...",
      "66.78.69.170 ip4:166.78.71.131 ip4:167.89.101.2 ip4:167.89.101.192/28 ip4:192.254.112.60 ip4:192.254..."
    ]
  },
  { type: "TXT", entries: [ "MS=6BF03E6AF5CB689E315FB6199603BABF2C88D805" ] },
  { type: "TXT", entries: [ "MS=ms44452932" ] },
  { type: "TXT", entries: [ "MS=ms58704441" ] },
  {
    type: "TXT",
    entries: [
      "adobe-idp-site-verification=b92c9e999aef825edc36e0a3d847d2dbad5b2fc0e05c79ddd7a16139b48ecf4b"
    ]
  }
]
```

**Review by kt3k — APPROVED** [review]
LGTM! Thanks!

**Review by bartlomieju — APPROVED** [review]
LGTM too, great work @cmorten, thank you!

**Pull request merged**
