### PR TITLE
chore(msgpack): get rid of testing/asserts usage

### PR DESCRIPTION
**Pull request by lino-levan**
Not sure how these slipped through the last removal PR. Maybe `msgpack` was originally written before deprecation and merged right after these were removed from the rest of std?

### CODE REVIEW

**Review by iuioiua — APPROVED** [review]
LGTM

**Comment by iuioiua** [comment]
Any chance this same thing was missed anywhere else in the codebase?

**Review by kt3k — APPROVED** [review]
LGTM. Thanks!

**Comment by lino-levan** [comment]
> Any chance this same thing was missed anywhere else in the codebase?

Not as far as I saw, could have happened with a different moved API though.

**Pull request merged**
