### PR TITLE
fix: don't use windows-xl runners, too expensive

### PR DESCRIPTION
**Pull request by ry**

### CODE REVIEW

**Comment by lino-levan** [comment]
LGTM

**Comment by iuioiua** [comment]
Should the same be done with the `ubuntu-20.04-xl` runner?

**Comment by lino-levan** [comment]
@iuioiua pricing for runners varies immensely depending on the OS

ref: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates

**Comment by iuioiua** [comment]
True. However, seeing as nothing particularly intensive is going on in the repo, `ubuntu-20.04-xl` may not be needed.

**Pull request merged**
