### PR TITLE
docs: instructions on how to add package title to title checker

### LINKED ISSUE #4727: new package contribution can't pass `Validate PR title` check

### PR DESCRIPTION
**Pull request by iuioiua**
Closes #4727

### CODE REVIEW

**Comment by kt3k** [comment]
It doesn't seem working to add a scope and use it in the same PR https://github.com/denoland/deno_std/pull/4733

**Comment by iuioiua** [comment]
Ah, yes. The package name has to be added to the `scopes` list in a preceding PR. I'll note that.

**Comment by kt3k** [comment]
So we are accepting a PR to add scope which doesn't exist yet?

**Comment by iuioiua** [comment]
Yes. We'd have to add the package name to the `scopes` list in the PR before the actual PR that implements the package.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
