### PR TITLE
Refactor WebSockets

### PR DESCRIPTION
**Pull request by sh7dm**
## **Changed:**
* Use assert.equal instead of deprecated assertEqual
* Replace let with const where possible
* Add WebSocketMessage type
* Make sha1 code style better
* Use OpCode in WebSocketFrame
* Use const where possible in WS
* Better code style in WS
* Separate sha1 tests, use const instead of let

### CODE REVIEW

**Comment by ry** [comment]
@sh7dm Can you get this to be green?

@keroxp Would you mind reviewing?

**Comment by sh7dm** [comment]
@ry why is it red? I can't understand log

**Comment by harrysarson** [comment]
It is red because in the `ws/test.ts` file the `assertEqual` import is deleted but is refered two (twice I think including once on line 145).

**Pull request merged**
