### PR TITLE
feat(node): add wasi module

### PR DESCRIPTION
**Pull request by talentlessguy**
since [Node.js WASI](https://nodejs.org/api/wasi.html#wasiinitializeinstance) is 1:1 to Deno WASI API, we can just re-export `Context`

### CODE REVIEW

**Comment by bartlomieju** [comment]
@talentlessguy can you enable some of the existing Node tests?

**Comment by kt3k** [comment]
Mostly looks good to me. @talentlessguy Can you also add the entry in `node/module_all.ts`?

**Comment by talentlessguy** [comment]
ok I will set node tests locally and add this entry to `modal_all.ts` soon

**Comment by kt3k** [comment]
Thanks. BTW I think it's ok to merge without native tests enabled as first pass if it requires too much work

**Review by kt3k — APPROVED** [review]
@talentlessguy LGTM. Thanks!

**Pull request merged**
