### PR TITLE
test(path): update test cases for canary

### LINKED ISSUE #774: 3 test cases fail with canary (2021-03-02)
These 3 test cases of `std/path` module seem failing with deno canary.

- [path] fromFileUrl (win32)
- [path] toFileUrl
- [path] toFileUrl (win32)

### PR DESCRIPTION
**Pull request by kt3k**
This PR disables some test assertions of `std/path` which started failing with canary today.

related to: https://github.com/denoland/deno/pull/9276

closes #774

### CODE REVIEW

**Comment by kitsonk** [comment]
Shouldn't we be fixing the code instead of disabling tests?

**Comment by kt3k** [comment]
@kitsonk I first thought of that, but the CI runs with both 1.7.5 and canary until 1.8 released. So I think it's difficult to update it to pass with both versions.

**Comment by lucacasonato** [comment]
> @kitsonk I first thought of that, but the CI runs with both 1.7.5 and canary until 1.8 released. So I think it's difficult to update it to pass with both versions.

I think we should disable this test in stable CI then and fix it in canary. It working on canary is more important than it working on stable IMO.

**Comment by kt3k** [comment]
> I think we should disable this test in stable CI then and fix it in canary. It working on canary is more important than it working on stable IMO.

hmm... OK, I'll try it.

**Comment by kt3k** [comment]
Introduced isCanary flag (`const isCanary = /\d\.\d\.\d\+[0-9a-f]{7}/.test(Deno.version.deno)`), and also merged #776, which is necessary to make CI green.

**Review by lucacasonato — APPROVED** [review]
LGTM - lets revert this right after 1.8 is released.

**Pull request merged**
