### PR TITLE
refactor(semver): remove runtime string type check in `parse()`

### PR DESCRIPTION
**Pull request by timreichen**
- removes runtime string type check in `parse()`
- refactors the function code

### CODE REVIEW

**Comment by iuioiua** [comment]
Related #3888

**Review by iuioiua — APPROVED** [review]
LGTM and I agree with the change. Though, Yoshiya might not.

**Comment by kt3k** [comment]
Now if you pass `undefined` to `parse`, the error message becomes `TypeError: Cannot read properties of undefined (reading 'length')` which is less intelligible than the current message `TypeError: version must be a string`. That is worse DX.

**Comment by iuioiua** [comment]
> Now if you pass `undefined` to `parse`, the error message becomes `TypeError: Cannot read properties of undefined (reading 'length')` which is less intelligible than the current message `TypeError: version must be a string`. That is worse DX.

I'm not disagreeing but it's worth noting that this only happens when types are ignored, such as when transpiled to JavaScript in browsers.

**Comment by timreichen** [comment]
> Now if you pass `undefined` to `parse`, the error message becomes `TypeError: Cannot read properties of undefined (reading 'length')` which is less intelligible than the current message `TypeError: version must be a string`. That is worse DX.

This particular check in this function is just random imo. There are lots of exported functions in semver that take strings, none of them have the runtime checks...
I think types should be enough. The type error states `Argument of type 'undefined' is not assignable to parameter of type 'string'`.

**Comment by kt3k** [comment]
I don't think type check by TS is enough. Deno supports JS by default, and if you use .js, you don't get type check error. Also there are many builtin APIs that return `any` values (e.g. `JSON.parse`, `response.json()`), and those values can be passed to `parse` without type error.

**Comment by timreichen** [comment]
> I don't think type check by TS is enough. Deno supports JS by default, and if you use .js, you don't get type check error. Also there are many builtin APIs that return `any` values (e.g. `JSON.parse`, `response.json()`), and those values can be passed to `parse` without type error.

Ok, I'll close this PR. 
I think we would profit greatly by having a std-wide solution for runtime checks. I could imagine a tool that checks all exported functions and adds missing runtime checks, at least for basic types. Something along the lines of:

```ts
export function someFunction(arg1: string, arg2?: number) {
 ...
}
```
=>
```ts
export function someFunction(arg1: string, arg2?: number) {
  runtimeTypeCheck("arg1", arg1, ["string"]);
  runtimeTypeCheck("arg2", arg2, ["number", "undefined"]);
}
```
WDYT?

**Comment by iuioiua** [comment]
> > I don't think type check by TS is enough. Deno supports JS by default, and if you use .js, you don't get type check error. Also there are many builtin APIs that return `any` values (e.g. `JSON.parse`, `response.json()`), and those values can be passed to `parse` without type error.
> 
> Ok, I'll close this PR. I think we would profit greatly by having a std-wide solution for runtime checks. I could imagine a tool that checks all exported functions and adds missing runtime checks, at least for basic types. Something along the lines of:
> 
> ```ts
> export function someFunction(arg1: string, arg2?: number) {
>  ...
> }
> ```
> 
> =>
> 
> ```ts
> export function someFunction(arg1: string, arg2?: number) {
>   runtimeTypeCheck("arg1", arg1, ["string"]);
>   runtimeTypeCheck("arg2", arg2, ["number", "undefined"]);
> }
> ```
> 
> WDYT?

A point of discussion for #3888.

**Pull request closed without merging**
