### PR TITLE
docs(testing): Add `Deprecated` tag for `assertThrowsSync` testing function

### PR DESCRIPTION
**Pull request by getspooky**

### CODE REVIEW

**Comment by zhangyuannie** [comment]
Do you think it might be better to simply rename the function in README since `assertRejects` is missing form it?
```diff
- - `assertThrowsAsync()` - Expects the passed `fn` to be async and throw (or
+ - `assertRejects()` - Expects the passed `fn` to be async and throw (or
```

**Comment by getspooky** [comment]
I think it would be good to keep the `assertThrowsAsync`.

**Comment by kt3k** [comment]
I agree with @zhangyuannie . Keeping deprecated item as a doc entry doesn't make sense to me.

I think the entry for `assertThrowsSync` should look like:
```
- `assertThrowsAsync()` - Deprecated. Use `assertRejects()` instead.
```

**Comment by caspervonb** [comment]
No point in documented deprecated things in the "manual".
Just document the new one, the old one still has a jsdoc entry until removed.

**Comment by bartlomieju** [comment]
This PR is superseded by #1198, thanks @getspooky but closing without merge.

**Pull request closed without merging**
