### PR TITLE
chore(crypto): upgrade dependencies

### PR DESCRIPTION
**Pull request by iuioiua**

### CODE REVIEW

**Comment by iuioiua** [comment]
@dsherret, do you know what this error is? https://github.com/denoland/deno_std/actions/runs/8460137322/job/23177768638?pr=4530

**Comment by dsherret** [comment]
Try just running `cargo build` in the directory.

**Comment by iuioiua** [comment]
I did - no files changed.

**Comment by dsherret** [comment]
Seems like it was just a rust toolchain version mismatch

**Comment by iuioiua** [comment]
😅 Thanks. LGTM.

**Review by dsherret — APPROVED** [review]
LGTM

**Pull request merged**
