### PR TITLE
Added the moment.js library.

### PR DESCRIPTION
**Pull request by lisniuse**
This moment.ts was ported from [moment@2.24.0](https://github.com/moment/moment).

### CODE REVIEW

**Comment by bartlomieju** [comment]
Moment.js is very opinionated and not lightweight. IMHO it's not a good option to vendor it in deno_std. @lisniuse would you consider turning it into standalone lib and adding it to [denoland/registry](https://github.com/denoland/registry)?

**Comment by zekth** [comment]
Agree for standalone port of moment.

**Comment by lisniuse** [comment]
> Moment.js is very opinionated and not lightweight. IMHO it's not a good option to vendor it in deno_std. @lisniuse would you consider turning it into standalone lib and adding it to [denoland/registry](https://github.com/denoland/registry)?

i see. sure!

**Comment by axetroy** [comment]
deno_std already have a `datetime` module.

If you need such a feature, it is recommended to add it to `datetime` module.

But it must be lightweight, functional interface

**Pull request closed without merging**
