### PR TITLE
Add more asserts

### PR DESCRIPTION
**Pull request by sh7dm**
Add some more asserts:
* `assertCloseTo`
* `assertDefined`
* `assertUndefined`
* `assertType`
* `assertArrayLength`
All of them have proper unit tests

### CODE REVIEW

**Comment by zekth** [comment]
Nice addition.
IMO the `assertArrayLength` is a bit too much and could be simply replaced by:
`assertEquals(foo.length,2)`

**Comment by ry** [comment]
Thanks @sh7dm - but I don't see the benefit of adding special assert functions for every type of assert. Are we also going to add `assertMapContains()` or `assertIs2()`? I think people will be fine with what exists currently. If you're developing some other code and feel the need for one of these, I'll be happy to consider them individually - but I think they should be argued on a case-by-case bases from here on out.

**Comment by sh7dm** [comment]
@ry check e.g. Jest docs. There are lots of asserts

**Comment by ry** [comment]
@sh7dm We're not trying to reimplement Jest. We're trying to keep things small.

I'd be happy to have this in an external repo https://github.com/denoland/registry/blob/master/src/database.json

**Comment by sh7dm** [comment]
@ry what's about mock functions? It will be nice to have them

**Comment by ry** [comment]
@sh7dm not sure - what would that look like? open an issue and we can discuss.

**Pull request closed without merging**
