### PR TITLE
refactor(io): restructure files for single exports

### PR DESCRIPTION
**Pull request by iuioiua**
This is a big PR that:
1. Separates the functions and classes/interfaces within the `std/io` module into their own individual files.
2. Deprecates the old function and class/locations for removal after v0.169.0.
3. Links imports within the standard library to the new function and class/interface locations.

This is part of #2936, which aims for leaner dependencies and a more straightforward structure.

### CODE REVIEW

**Comment by iuioiua** [comment]
The node test failure appears to be unrelated to this change.

**Comment by iuioiua** [comment]
I'll resolve conflicts if and once it's agreed upon that this PR looks like a good idea.

**Comment by kt3k** [comment]
I'm in favor of this change. This reduces unnecessary deps in std's dependency tree. This seems an improvement of module load footprint.

Does anyone have any concern on this chage?

**Comment by cjihrig** [comment]
No concerns from me.

**Comment by iuioiua** [comment]
Happy to hear you guys are for this PR. There are too many conflicts with the main branch. I'll redo this change in a new PR.

**Pull request closed without merging**
