### PR TITLE
refactor: switch the Deno.spawn

### PR DESCRIPTION
**Pull request by crowlKats**
needs API stabilization first. This PR does not change node's child_process.

### CODE REVIEW

**Comment by kt3k** [comment]
Oh, nice! `+265 −431`

Can you make the test passing?

**Comment by crowlKats** [comment]
nothing will really pass except if we use unstable everywhere. better to just wait till next minor when it hopefully is stable

**Comment by crowlKats** [comment]
Blocked on https://github.com/whatwg/streams/issues/1212, except if we just disable the op sanitizers for some tests

**Comment by crowlKats** [comment]
Will disable the op sanitizer for the tests that are blocked on the spec change, and re-enable it once said spec change lands

**Review by bartlomieju — APPROVED** [review]
LGTM, nice work Leo

**Review by kt3k — APPROVED** [review]
LGTM!

**Pull request merged**
