### PR TITLE
feat(crypto): `createHash` utility

### PR DESCRIPTION
**Pull request by iuioiua**
This PR introduces the `createHash` utility, which takes care of the usual boilerplate of creating hashes.

Its practical uses can be seen within `http/file_server.ts` and `http/file_server_test.ts`.

I can understand if this utility is too trivial to be public. However, it may still be helpful internally.

### CODE REVIEW

**Comment by cjihrig** [comment]
I think we should start with this as an internal utility for a while and see if it warrants being added to the public API, but other than that the code here LGTM.

**Comment by kt3k** [comment]
> I think we should start with this as an internal utility for a while and see if it warrants being added to the public API

I agree with this opinion. I'm not sure it's worth the public API as it looks a little trivial. Let's make it private at this point.

**Comment by iuioiua** [comment]
No problems. I've now made `createHash` private.

**Comment by cjihrig** [comment]
Would you mind rebasing to pick up a fix for the CI failures.

**Review by cjihrig — APPROVED** [review]

**Pull request merged**
