### PR TITLE
feat(collections): add `aggregateGroups`

### PR DESCRIPTION
**Pull request by LionC**
This adds tests and fixed the comments from #1188

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
Thanks for pushing this through @LionC; should the `README` be updated as well?

**Comment by LionC** [comment]
Yes, yes we should 🙈

Will do

**Review by kt3k — APPROVED** [review]
LGTM. Nice work!

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @LionC

**Pull request merged**
