### PR TITLE
docs: reorganize docs

### PR DESCRIPTION
**Pull request by crowlKats**
To improve documentation experience on https://deno.land/std

Todo:
- [x] move remaining things in async readme to async/abortable.ts
- [ ] `collections`: document arguments and return values with corresponding jsdoc tags
- [ ] `collections/deep_merge.ts`: document second overload
- [ ] `collections/max_by.ts`: document second, third & fourth overload
- [ ] `collections/max_of.ts`: document second overload
- [ ] `collections/min_by.ts`: document second, third & fourth overload
- [ ] `collections/min_of.ts`: document second overload
- [ ] `collections/sort_by.ts`: document second, third & fourth overload
- [ ] `encoding/csv.ts`: document second, third, fourth & fifth overload
- [ ] `encoding/_yaml/parse.ts`: document second overload
- [ ] figure out how to document `path`

### CODE REVIEW

**Comment by iuioiua** [comment]
Hi @crowlKats, this seems like a fairly big PR, even though it provides some real nice cleanups.

Might it instead be a better idea to break this up into smaller PRs, perhaps one per module? Doing so would make it easier and simpler to make progress on documentation.

I'd be more than happy to help!

**Comment by crowlKats** [comment]
@iuioiua the PR is pretty much done, as all points except first and last one can be left for follow-ups. the last point is currently blocked upstream in a deno_doc PR.

**Comment by crowlKats** [comment]
last requirement for this PR is for doc_components to render examples.

**Review by kt3k — APPROVED** [review]
Great! Now the JSDocs are the single source of std documentation.

LGTM. Nice work!

**Pull request merged**
