### PR TITLE
chore(ci): test on stable

### PR DESCRIPTION
**Pull request by iuioiua**
This change ensures CI passes on the latest stable release of Deno.

### CODE REVIEW

**Comment by kt3k** [comment]
Compatibility with stable deno is sometimes very difficult to keep (if deno canary has some changes with breaking nature), and in that case we have to prioritize canary (The latest CLI release needs to pass the latest std test cases). That is the reason we only run canary in std CI.

refs:
- https://github.com/denoland/deno_std/issues/870
- https://github.com/denoland/deno_std/pull/2991

(I think there was also a case where it was impossible to pass both canary and stable CI in the past, but I don't find it now..)

**Comment by iuioiua** [comment]
> (I think there was also a case where it was impossible to pass both canary and stable CI in the past, but I don't find it now..)

Yeah, I agree. To elaborate, this would be because the Deno and Standard Library APIs are becoming more stable over time.

**Comment by iuioiua** [comment]
This PR is ready for review.

**Comment by kt3k** [comment]
I think we should start CI with stable CLI when we released stable version of std. ref https://github.com/denoland/deno_std/issues/3489

**Comment by iuioiua** [comment]
Actually, I think we should merge this before v1, so it's confirmed working fine for v1.

**Review by kt3k — APPROVED** [review]
Let's try and see.

**Comment by kt3k** [comment]
ref https://github.com/denoland/deno_std/pull/3119

**Pull request merged**
