### PR TITLE
Fix prettier WIP

### PR DESCRIPTION
**Pull request by ry**
cc @kt3k 

prettier is broken on deno master

### CODE REVIEW

**Comment by kt3k** [comment]
It seems that `walk('.', { match })` only looks up the files under `cwd`. So it doesn't work with the absolute paths as in the test case of `./tools/fmt_test.py`

**Comment by bartlomieju** [comment]
Maybe throw an error when files are passed to prettier and they don't exist instead of silent pass?

**Comment by kt3k** [comment]
There are 2 problems:
1. walk('.') only walks under the current dir. If the target is out of the current dir, it doesn't work.
2. checking of paths are done by the given expression, not by the actual path equality. (For example `pwd`/a.js doesn't match with ./a.js, because they are different as strings.)

**Comment by kt3k** [comment]
I think it's better to do some workaround in //tools/fmt_test.py (in denoland/deno) at the moment because these require some careful works to address.

**Pull request closed without merging**
