### PR TITLE
BREAKING(encoding): replace `Ascii85Options` with `EncodeAscii85Options` and `DecodeAscii85Options`

### PR DESCRIPTION
**Pull request by iuioiua**
This change deprecates `Ascii85Options` in favor of `EncodeAscii85Options` and `DecodeAscii85Options`. Previously, these were used for both `encodeAscii85()` and `decodeAscii85()`, but the latter didn't use the `delimiter` property.

### CODE REVIEW

**Comment by kt3k** [comment]
Looks like technically a breaking change. Let's land together with `1.0.0-rc.1` PR to not break the user's program.

**Comment by iuioiua** [comment]
What does this break?

**Comment by kt3k** [comment]
Doesn't `decodeAscii85(str, { delimiter: true })` cause type error now?

**Review by kt3k — APPROVED** [review]
LGTM

**Review by kt3k — APPROVED** [review]
LGTM again!

**Pull request merged**
