### PR TITLE
chore(semver): literal regular expressions

### PR DESCRIPTION
**Pull request by timreichen**
The ported semver code is a bit stale and does not make use of some newer js features.
This is one of a few upcoming PRs to improve the overall code base in semver.

This PRs reduces the codebase in semver, makes it more efficient and readable while preserving functionality.
- replace regular expression constructions with regular expression literals
- add and use named capturing groups

**Note**: The regular expressions may look a bit wild atm. But `XRANGE_REGEXP`, `TILDE_REGEXP` and `CARET_REGEXP` will be reduced to one generic `OPERATOR_REGEXP` in a future PR.

### CODE REVIEW

**Comment by kt3k** [comment]
These regexps look harder to maintain than the existing state to me. The current code builds large regexps from smaller parts, but this version expand everything in literal and seems causing lot of repetitions of the same patterns.

**Comment by timreichen** [comment]
> These regexps look harder to maintain than the existing state to me.

I actually had a harder time grasping what exactly was going on with all these regexp fragments than reading the actual regexp.
The literal regexp is easy to maintain, especially since it can be compared directly to the regexp on [semver.org](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string).

> The current code builds large regexps from smaller parts, but this version expand everything in literal and seems causing lot of repetitions of the same patterns.

Yes at the current state, but

> Note: The regular expressions may look a bit wild atm. But XRANGE_REGEXP, TILDE_REGEXP and CARET_REGEXP will be reduced to one generic OPERATOR_REGEXP in a future PR.

So these regexps can be combined instead of using duplications. I thought it would be better to split that into a separate PR, but I could also update this PR if you want.

**Comment by timreichen** [comment]
@kt3k should I update the pr so it includes the proposed combinig of the regexps?

**Comment by kt3k** [comment]
What would be the goal in that case?

**Comment by iuioiua** [comment]
> To reduce the number of needed regexps and thus reducing repetitions. This allows for a switch statement for the operator instead of many match tries.
> 
> All in all this reduces the needed lines of code by 150-200 lines.

Will this make the semver API easier to understand? If so, it might be worth doing in this PR. Are you also able to fix the merge conflict? I'm still unsure about this PR too.

**Comment by timreichen** [comment]
> Will this make the semver API easier to understand? If so, it might be worth doing in this PR. Are you also able to fix the merge conflict? I'm still unsure about this PR too.

I think so. This makes it possible to optimize certain parts of the api.

**Comment by kt3k** [comment]
Repeating my first comment. I think the below huge regexps are unmanageable / unmaintainable.

```js
export const FULL_REGEXP =
  /^v?(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/;
export const XRANGE_REGEXP =
  /^(?<operator>(?:<|>)?=?)\s*[v=\s]*(?<major>0|[1-9]\d*|x|X|\*)(?:\.(?<minor>0|[1-9]\d*|x|X|\*)(?:\.(?<patch>0|[1-9]\d*|x|X|\*)(?:(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*))*)))?(?:\+(?<buildmetadata>[\da-zA-Z-]+(?:\.[\da-zA-Z-]+)*))?)?)?$/;
export const TILDE_REGEXP =
  /^(?<operator>~>?)[v=\s]*(?<major>0|[1-9]\d*|x|X|\*)(?:\.(?<minor>0|[1-9]\d*|x|X|\*)(?:\.(?<patch>0|[1-9]\d*|x|X|\*)(?:(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*))*)))?(?:\+(?<buildmetadata>[\da-zA-Z-]+(?:\.[\da-zA-Z-]+)*))?)?)?$/;
export const CARET_REGEXP =
  /^(?<operator>\^)[v=\s]*(?<major>0|[1-9]\d*|x|X|\*)(?:\.(?<minor>0|[1-9]\d*|x|X|\*)(?:\.(?<patch>0|[1-9]\d*|x|X|\*)(?:(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*))*)))?(?:\+(?<buildmetadata>[\da-zA-Z-]+(?:\.[\da-zA-Z-]+)*))?)?)?$/;
export const COMPARATOR_REGEXP =
  /^(?<operator>(?:<|>)?=?)\s*(v?(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*))*))?(?:\+(?<buildmetadata>[\da-zA-Z-]+(?:\.[\da-zA-Z-]+)*))?)$|^$/;
export const HYPHENRANGE_REGEXP =
  /^\s*([v=\s]*(?<semver>0|[1-9]\d*|x|X|\*)(?:\.(0|[1-9]\d*|x|X|\*)(?:\.(0|[1-9]\d*|x|X|\*)(?:(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*))*)))?(?:\+([\da-zA-Z-]+(?:\.[\da-zA-Z-]+)*))?)?)?)\s+-\s+([v=\s]*(0|[1-9]\d*|x|X|\*)(?:\.(0|[1-9]\d*|x|X|\*)(?:\.(0|[1-9]\d*|x|X|\*)(?:(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z0-9-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z0-9-]*))*)))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)?)?)\s*$/;
export const STAR_REGEXP = /(?<operator>(<|>)?=?)\s*\*/;
```

>> Note: The regular expressions may look a bit wild atm. But XRANGE_REGEXP, TILDE_REGEXP and CARET_REGEXP will be reduced to one generic OPERATOR_REGEXP in a future PR.
>
> So these regexps can be combined instead of using duplications. I thought it would be better to split that into a separate PR, but I could also update this PR if you want.

I guess this suggestion makes the regexp further bigger. I don't think that improve the meatainability/readability.

**Comment by timreichen** [comment]
> Repeating my first comment. I think the below huge regexps are unmanageable / unmaintainable.

I updated the regexes, they look like this now could be reduced to three:
```ts
export const FULL_REGEXP =  /^v?(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/;
export const SEMVER_REGEXP =  /^[v=\s]*(?<major>0|[1-9]\d*|x|X|\*)(?:\.(?<minor>0|[1-9]\d*|x|X|\*)(?:\.(?<patch>0|[1-9]\d*|x|X|\*)(?:(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][a-zA-Z\d-]*))*)))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)?)?/;
export const OPERATOR_REGEXP = /^(?<operator>~>?|\^|(?:<|>)?=?)\s*/;

```
Do you still think they are unmaintainable? I think they are well readable because they use named capturing groups.
And they can be compared to the semver spec which provide full regexps: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

But if this is still a problem, this could be written like this:
```ts
const prereleasePart = `(?:-(?<prerelease>(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))`;
const buildmetaPart = `(?:\\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))`;
export const FULL_REGEXP = new RegExp(`^v?(?<major>0|[1-9]\\d*)\\.(?<minor>0|[1-9]\\d*)\\.(?<patch>0|[1-9]\\d*)${prereleasePart}?${buildmetaPart}?$`);
export const SEMVER_REGEXP = new RegExp(`^[v=\\s]*(?<major>0|[1-9]\\d*|x|X|\\*)(?:\\.(?<minor>0|[1-9]\\d*|x|X|\\*)(?:\\.(?<patch>0|[1-9]\\d*|x|X|\\*)${prereleasePart}?${buildmetaPart}?)?)?`,
);
export const OPERATOR_REGEXP = /^(?<operator>~>?|\^|(?:<|>)?=?)\s*/;
```
though I think this doesn't make it necessarily more readable.

**Comment by kt3k** [comment]
They still look really hard to understand, and looks worse for readability. The existing version has a lot of comments to each small part of regexp, which helps understanding them. With everything written in single line regexp, the maintainers/contributors need to understand everything from just literal regexp, which is much unfriendly in my opinion. Especially where the parens are balanced in these long regexps are hard to grasp

**Pull request closed without merging**
