### PR TITLE
Add TypeScript (3.5.1)

### PR DESCRIPTION
**Pull request by kitsonk**
Refs #428 

This is an MVP for supporting TypeScript as part of the std library.

It is a copy of the `typescript/lib` in `typescript/vendor` with and addition to the `./vendor/typescript.js` so that it properly exposes itself globally when loaded in Deno.  It also requires https://github.com/denoland/deno/commit/c30decab77c4ebeb34ebd1d73b0f45bb26944c79 or later to work properly.

### CODE REVIEW

**Comment by brandonros** [comment]
Any idea why CI/CD would be failing?

**Comment by kitsonk** [comment]
> Any idea why CI/CD would be failing?

Yeah, as mentioned, it needs a new version of Deno to be updated in CI, then I need to rebase the PR.

**Comment by hayd** [comment]
Can this be a git submodule? Then when deno_std is migrated to deno it could be a symlink.

**Comment by zekth** [comment]
> Can this be a git submodule? Then when deno_std is migrated to deno it could be a symlink.

As the move is coming in a short amount of time, this patch is not really usefull i think.

**Comment by kitsonk** [comment]
> As the move is coming in a short amount of time, this patch is not really usefull i think.

As it stands no. It was more to show how we would solve #428.  @ry asked me specifically to look at it.  I got it working, but I was leaving Ry to comment on it to any degree he felt he wanted to.

**Pull request closed without merging**
