### PR TITLE
refactor(semver): move `isOperator` to separate file

### PR DESCRIPTION
**Pull request by timreichen**

### CODE REVIEW

**Review by iuioiua — CHANGES_REQUESTED** [review]
Perhaps, this should be `_shared_test.ts`.

**Comment by timreichen** [comment]
> Perhaps, this should be `_shared_test.ts`.

Maybe we can move `isOperator` to a separate file?

**Comment by iuioiua** [comment]
SGTM. Maybe we should also review other internal dependencies in the same way for `std/semver`. See #3916 and #4007 for an idea of what I mean.

**Comment by timreichen** [comment]
> SGTM. Maybe we should also review other internal dependencies in the same way for `std/semver`. See #3916 and #4007 for an idea of what I mean.

Agreed. There is definitely room for improvement. I'll take a look.

**Review by iuioiua — CHANGES_REQUESTED** [review]
We should prefix these files with an underscore as `isOperator()` is part of the private API. Right?

**Comment by timreichen** [comment]
> We should prefix these files with an underscore as `isOperator()` is part of the private API. Right?

done

**Comment by iuioiua** [comment]
Hey Tim, upon reviewing this PR, I realised that the whole `isOperator()` doesn't seem needed. I'll close this in favour of #4038. Sorry, I should've realised this earlier. Either way, thanks for the PR. Please feel free to review the other PR.

**Pull request closed without merging**
