### PR TITLE
Chore : Add require jsdoc

### PR DESCRIPTION
**Pull request by zekth**
Following https://github.com/denoland/deno_std/pull/459
Due to old age of branch, easier to restart from fresh one.

As you can see there is stuff to do, but not so much.

### CODE REVIEW

**Comment by j-f1** [comment]
<details><summary>Missing JSDoc comments</summary>

- [`encoding/csv.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/encoding/csv.ts)
  - [ ] [110](https://github.com/denoland/deno_std/tree/89dfdb58/encoding/csv.ts#L110)
- [`encoding/hex.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/encoding/hex.ts)
  - [ ] [10](https://github.com/denoland/deno_std/tree/89dfdb58/encoding/hex.ts#L10)
  - [ ] [17](https://github.com/denoland/deno_std/tree/89dfdb58/encoding/hex.ts#L17)
- [`encoding/toml.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/encoding/toml.ts)
  - [ ] [557](https://github.com/denoland/deno_std/tree/89dfdb58/encoding/toml.ts#L557)
  - [ ] [561](https://github.com/denoland/deno_std/tree/89dfdb58/encoding/toml.ts#L561)
- [`flags/mod.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/flags/mod.ts)
  - [ ] [55](https://github.com/denoland/deno_std/tree/89dfdb58/flags/mod.ts#L55)
- [`fmt/colors.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts)
  - [ ] [24](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L24)
  - [ ] [32](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L32)
  - [ ] [50](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L50)
  - [ ] [54](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L54)
  - [ ] [58](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L58)
  - [ ] [62](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L62)
  - [ ] [66](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L66)
  - [ ] [70](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L70)
  - [ ] [74](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L74)
  - [ ] [78](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L78)
  - [ ] [82](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L82)
  - [ ] [86](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L86)
  - [ ] [90](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L90)
  - [ ] [94](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L94)
  - [ ] [98](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L98)
  - [ ] [102](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L102)
  - [ ] [106](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L106)
  - [ ] [110](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L110)
  - [ ] [114](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L114)
  - [ ] [118](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L118)
  - [ ] [122](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L122)
  - [ ] [126](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L126)
  - [ ] [130](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L130)
  - [ ] [134](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L134)
  - [ ] [138](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L138)
  - [ ] [142](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L142)
  - [ ] [146](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/colors.ts#L146)
- [`fmt/sprintf.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/sprintf.ts)
  - [ ] [671](https://github.com/denoland/deno_std/tree/89dfdb58/fmt/sprintf.ts#L671)
- [`fs/glob.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/fs/glob.ts)
  - [ ] [99](https://github.com/denoland/deno_std/tree/89dfdb58/fs/glob.ts#L99)
  - [ ] [123](https://github.com/denoland/deno_std/tree/89dfdb58/fs/glob.ts#L123)
- [`fs/write_json.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/fs/write_json.ts)
  - [ ] [11](https://github.com/denoland/deno_std/tree/89dfdb58/fs/write_json.ts#L11)
  - [ ] [33](https://github.com/denoland/deno_std/tree/89dfdb58/fs/write_json.ts#L33)
- [`http/server.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/http/server.ts)
  - [ ] [26](https://github.com/denoland/deno_std/tree/89dfdb58/http/server.ts#L26)
  - [ ] [60](https://github.com/denoland/deno_std/tree/89dfdb58/http/server.ts#L60)
  - [ ] [234](https://github.com/denoland/deno_std/tree/89dfdb58/http/server.ts#L234)
  - [ ] [286](https://github.com/denoland/deno_std/tree/89dfdb58/http/server.ts#L286)
  - [ ] [388](https://github.com/denoland/deno_std/tree/89dfdb58/http/server.ts#L388)
  - [ ] [395](https://github.com/denoland/deno_std/tree/89dfdb58/http/server.ts#L395)
- [`installer/mod.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/installer/mod.ts)
  - [ ] [138](https://github.com/denoland/deno_std/tree/89dfdb58/installer/mod.ts#L138)
  - [ ] [198](https://github.com/denoland/deno_std/tree/89dfdb58/installer/mod.ts#L198)
- [`io/util.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/io/util.ts)
  - [ ] [10](https://github.com/denoland/deno_std/tree/89dfdb58/io/util.ts#L10)
  - [ ] [20](https://github.com/denoland/deno_std/tree/89dfdb58/io/util.ts#L20)
  - [ ] [24](https://github.com/denoland/deno_std/tree/89dfdb58/io/util.ts#L24)
- [`log/levels.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/log/levels.ts)
  - [ ] [20](https://github.com/denoland/deno_std/tree/89dfdb58/log/levels.ts#L20)
  - [ ] [24](https://github.com/denoland/deno_std/tree/89dfdb58/log/levels.ts#L24)
- [`log/mod.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/log/mod.ts)
  - [ ] [51](https://github.com/denoland/deno_std/tree/89dfdb58/log/mod.ts#L51)
  - [ ] [76](https://github.com/denoland/deno_std/tree/89dfdb58/log/mod.ts#L76)
- [`multipart/formfile.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/multipart/formfile.ts)
  - [ ] [22](https://github.com/denoland/deno_std/tree/89dfdb58/multipart/formfile.ts#L22)
- [`prettier/util.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/prettier/util.ts)
  - [ ] [5](https://github.com/denoland/deno_std/tree/89dfdb58/prettier/util.ts#L5)
- [`testing/asserts.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/testing/asserts.ts)
  - [ ] [68](https://github.com/denoland/deno_std/tree/89dfdb58/testing/asserts.ts#L68)
  - [ ] [321](https://github.com/denoland/deno_std/tree/89dfdb58/testing/asserts.ts#L321)
- [`testing/diff.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/testing/diff.ts)
  - [ ] [37](https://github.com/denoland/deno_std/tree/89dfdb58/testing/diff.ts#L37)
- [`testing/format.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/testing/format.ts)
  - [ ] [527](https://github.com/denoland/deno_std/tree/89dfdb58/testing/format.ts#L527)
- [`testing/mod.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/testing/mod.ts)
  - [ ] [98](https://github.com/denoland/deno_std/tree/89dfdb58/testing/mod.ts#L98)
  - [ ] [113](https://github.com/denoland/deno_std/tree/89dfdb58/testing/mod.ts#L113)
  - [ ] [365](https://github.com/denoland/deno_std/tree/89dfdb58/testing/mod.ts#L365)
- [`testing/runner.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/testing/runner.ts)
  - [ ] [155](https://github.com/denoland/deno_std/tree/89dfdb58/testing/runner.ts#L155)
- [`textproto/mod.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/textproto/mod.ts)
  - [ ] [25](https://github.com/denoland/deno_std/tree/89dfdb58/textproto/mod.ts#L25)
- [`util/async.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/util/async.ts)
  - [ ] [111](https://github.com/denoland/deno_std/tree/89dfdb58/util/async.ts#L111)
- [`util/deep_assign.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/util/deep_assign.ts)
  - [ ] [2](https://github.com/denoland/deno_std/tree/89dfdb58/util/deep_assign.ts#L2)
- [`uuid/mod.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/uuid/mod.ts)
  - [ ] [6](https://github.com/denoland/deno_std/tree/89dfdb58/uuid/mod.ts#L6)
- [`uuid/v4.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/uuid/v4.ts)
  - [ ] [8](https://github.com/denoland/deno_std/tree/89dfdb58/uuid/v4.ts#L8)
  - [ ] [12](https://github.com/denoland/deno_std/tree/89dfdb58/uuid/v4.ts#L12)
- [`ws/mod.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/ws/mod.ts)
  - [ ] [35](https://github.com/denoland/deno_std/tree/89dfdb58/ws/mod.ts#L35)
  - [ ] [43](https://github.com/denoland/deno_std/tree/89dfdb58/ws/mod.ts#L43)
  - [ ] [51](https://github.com/denoland/deno_std/tree/89dfdb58/ws/mod.ts#L51)
  - [ ] [60](https://github.com/denoland/deno_std/tree/89dfdb58/ws/mod.ts#L60)
- [`xeval/mod.ts`](https://github.com/denoland/deno_std/tree/89dfdb58/xeval/mod.ts)
  - [ ] [118](https://github.com/denoland/deno_std/tree/89dfdb58/xeval/mod.ts#L118)
</details>

<details><summary><small>Generated using PEG.js</small></summary>

```js
File = blocks: Block+ {
  return blocks.map(({ path, lines }) =>
    `- [\`${path}\`](https://github.com/denoland/deno_std/tree/89dfdb58/${path})\n` +
    lines.map(l => `  - [ ] [${l}](https://github.com/denoland/deno_std/tree/89dfdb58/${path}#L${l})`).join('\n')
  ).join('\n')
}

Block = path: Path "\n" lines: Err+ "\n" { return { path, lines } }

Path = "/home/vsts/work/1/s/" path: $[^\n]+ { return path }
Err = " "+ line: $[0-9]+ ":" col: $[0-9]+ [^\n]+ "\n" { return line }
```
</details>

**Comment by zekth** [comment]
thanks @j-f1 for this. So help welcome to make those jsdoc comments :)

**Comment by ry** [comment]
@zekth I've merged deno_std into denoland/deno. I think this PR is very far from being landed, but if you do more work on it, please resubmit there. Sorry for the extra work!

**Comment by j-f1** [comment]
Do you want to update the repo description/url to announce its deprecation and new location, then archive it so people don’t accidentally open issues and such?

**Pull request closed without merging**
