### PR TITLE
docs (collections): Avoid using relative paths in import statements in code examples

### PR DESCRIPTION
**Pull request by ayame113**
Currently, relative paths are used in the import statement in some code examples.
Change this to import from https.

### CODE REVIEW

**Comment by LionC** [comment]
If that works with `deno test`, I am all for it

**Comment by LionC** [comment]
Oh sorry, I thought you changed that in the actual function JSDocs. That might actually be a good idea - as they are what is being displayed on doc.deno.land

Would you consider refactoring that here as well?

**Comment by ayame113** [comment]
I also changed the import statement in JSDoc.
Although it makes document testing difficult locally, I'm in favor of modifying JSDoc to improve the display of the document.

**Review by kt3k — APPROVED** [review]
I agree with this change. This makes more sense to the readers of the docs. LGTM

**Pull request merged**
