### PR TITLE
BREAKING(csv): use `LF` instead of `CRLF`

### PR DESCRIPTION
**Pull request by fdemir**
Fixes https://github.com/denoland/deno_std/issues/4546#issue-2224115477

### CODE REVIEW

**Comment by fdemir** [comment]
Removing CLRF and make the world bettter place.

**Review by iuioiua — CHANGES_REQUESTED** [review]
I'm for this change. Modern OSs handle LF fine, and this is one less character. The use of LF also seems more prevalent. However, this is a breaking change of a stable API. This PR should be landed in 1.0.

Either way, please resolve the test failures.

**Comment by kt3k** [comment]
@fdemir Can you split the fix for #4546 and breaking change of CRLF to LF into different PRs?

**Comment by iuioiua** [comment]
If CRLF is what the spec defines, let's not make this specific change. The other suggestion in #4546 makes sense, though. @kt3k, please close if you agree.

**Pull request closed without merging**
