### PR TITLE
feat(node): process.stdin.setRawMode

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM. Nice!

**Review by kt3k — DISMISSED** [review]
Oops, tests are failing in ubuntu and mac with `Uncaught BadResource: ENOTTY: Not a typewriter`

We might need to simulate tty environment somehow in CI?

**Comment by kt3k** [comment]
I think it'd be ok to skip test for the time being with an issue for it being created

**Comment by bartlomieju** [comment]
> I think it'd be ok to skip test for the time being with an issue for it being created

Done, opened https://github.com/denoland/deno_std/issues/1579

**Comment by bartlomieju** [comment]
@kt3k please approve again

**Review by kt3k — APPROVED** [review]
LGTM. Thanks for creating the issue 👍

**Pull request merged**
