### PR TITLE
docs(path): clarify the meaning of resolve for normalize

### PR DESCRIPTION
**Pull request by jflatow**
Addresses #2918.

### CODE REVIEW

**Comment by kt3k** [comment]
The doc looks good to me, but does the same note apply to `normalize` in `path/win32.ts`?

**Comment by jflatow** [comment]
> The doc looks good to me, but does the same note apply to `normalize` in `path/win32.ts`?

I'm not sure and I can't test it, so I left it off

**Review by kt3k — APPROVED** [review]
LGTM

**Review by cjihrig — APPROVED** [review]
LGTM. I think we'll have to wait to merge until the CI is fixed.

**Pull request merged**
