### PR TITLE
feat(collections): Add BSTree and RBTree

### PR DESCRIPTION
**Pull request by KyleJune**
Deno has an internal RBTree that is implemented in JavaScript and can't be exposed. I think it would be useful to have a RBTree available in the std/collections. As mentioned in my [feat(collections): Add BinaryHeap](https://github.com/denoland/deno_std/pull/2022) PR, the mock module makes use of RBTree internally to help with mocking time more accurately. Having this available in std would make it easier to add mock to std/testing without having any third party dependencies.

Below are links to the deno docs for the 3 files added as part of this PR.

- [bs_tree](https://doc.deno.land/https://raw.githubusercontent.com/KyleJune/deno_std/kj-add-binary-search-trees/collections/bs_tree.ts)
- [rb_tree](https://doc.deno.land/https://raw.githubusercontent.com/KyleJune/deno_std/kj-add-binary-search-trees/collections/rb_tree.ts)
- [comparators](https://doc.deno.land/https://raw.githubusercontent.com/KyleJune/deno_std/kj-add-binary-search-trees/collections/comparators.ts) \(same as from my BinaryHeap PR\)

There was [a comment](https://github.com/denoland/deno_std/pull/2022#discussion_r825362339) on my BinaryHeap PR regarding removing comparators.ts. Depending on responses from my last comments, I'll make the requested changes to this PR as well.

I didn't re-export bs_node.ts or rb_node.ts from mod.ts because they are just used internally by BSTree and RBTree.

### CODE REVIEW

**Comment by bartlomieju** [comment]
LGTM, @kt3k do you think we could land this one?

**Comment by KyleJune** [comment]
I'll fix the merge conflict issue.

**Comment by KyleJune** [comment]
The conflicts were that `comparators.ts` and `comparators_test.ts` had underscore prefixes added to them. I also updated the `rb_tree_test.ts` file to start using `_test_utils.ts` instead of re-implementing `MyMath` and `Container`.

The comparators are exported from `binary_heap.ts`, `bs_tree.ts`, and `rb_tree.ts` because the comparators are commonly used with them. The examples I added to the `README.md` demonstrate their usefulness. For the words tree, I have it sort first by number of letters then fall back to sorting the text contents of the strings when they are of equal length.

**Comment by KyleJune** [comment]
Forgot to run deno test with the --doc flag. Missed importing RBTree instead of BSTree in the BSTree example. I believe CI should pass now.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @KyleJune

**Pull request merged**
