### PR TITLE
BREAKING: remove deprecated `std/hash` module

### LINKED ISSUE #2733: review `std/crypto` and `std/hash`
Continuing the discussion from #2719, `std/hash` shouldn't be fully deprecated due to its desired streaming functionality that isn't yet available as a web spec. [Although, it's planned to one day be.](https://github.com/wintercg/proposal-webcrypto-streams)

However, `std/hash` does overlap with `std/crypto` in a few ways. I have a few suggestions that I think would prune some of this overlapped functionality:
1. Move stream-based functionality within `std/hash` to `std/crypto/streams`.
2. Deprecate APIs within `std/hash` that exist within `std/crypto`.
3. Move some `Hasher` methods such as `toString` as pure functions in `std/crypto`.

Put simply; I suggest we merge `std/hash` into `std/crypto`. Doing so would get rid of duplicate code and maintain streaming support. @kt3k and @cjihrig, what do you guys think?

### PR DESCRIPTION
**Pull request by iuioiua**
This PR removes the `std/hash` module, which has been deprecated for a few months now, in favour of `std/crypto`.

Best that #2767 and #2766 (possibly) land first before pushing this change to cover all bases.

Closes #2733.

### CODE REVIEW

**Review by cjihrig — APPROVED** [review]
Code LGTM and the suggested prerequisite PRs have been merged. I'll merge this on Monday to give @kt3k, @bartlomieju, or anyone else a final chance to weigh in.

**Review by kt3k — APPROVED** [review]
LGTM. Thanks for working on this!

**Review by bartlomieju — APPROVED** [review]
LGTM too!

**Comment by cjihrig** [comment]
I guess I'll just land this now since all requested reviews are in.

**Review by randydwhitephotography — COMMENTED** [review]
dont lknow

**Review by randydwhitephotography — COMMENTED** [review]
test

**Comment by cjihrig** [comment]
I have reported the previous comments as spam to GitHub.

**Pull request merged**
