### PR TITLE
feat(semver): canParse

### LINKED ISSUE #3707: SemVer: Method returning boolean for validation
I used to use `semver.valid` to check if a string is a valid semver. Since the deprecation of the old library, is there a similar method which returns a boolean? I prefer Booleans compared to TypeErrors, what `semver.parse` throws.

If not, can we add one?

Thank you!

### PR DESCRIPTION
**Pull request by lino-levan**
closes #3707

### CODE REVIEW

**Review by iuioiua — APPROVED** [review]
LGTM

**Comment by lino-levan** [comment]
This flaky test makes me sad :(

**Comment by timreichen** [comment]
How about just testing against a regexp?

**Comment by lino-levan** [comment]
> How about just testing against a regexp?

Unfortunately it's not that simple (there are a lot of other things to test). This is, in my opinion, the cleanest way of doing it. Anything else would require a lot of duplicated logic.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
