### PR TITLE
docs(data-structures): improve documentation

### PR DESCRIPTION
**Pull request by lucacasonato**
This commit completes documentation for the `@std/data-structures` module.

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
Looks great!

**Comment by iuioiua** [comment]
Sorry, it looks like a rebase is needed after the revert.

**Comment by iuioiua** [comment]
Let me submit a PR to remove the leaky abstractions.

**Comment by kt3k** [comment]
> Let me submit a PR to remove the leaky abstractions.

I'll land this for now when CI passed. I think that makes further work easier

**Pull request merged**
