### PR TITLE
refactor(semver): replace `parseComparator()` with comparator objects

### PR DESCRIPTION
**Pull request by timreichen**

### CODE REVIEW

**Review by iuioiua — CHANGES_REQUESTED** [review]
Mostly LGTM. Are you able to add return types to the affected functions? It'd make the purpose of this PR a little clearer.

**Comment by timreichen** [comment]
> Mostly LGTM. Are you able to add return types to the affected functions? It'd make the purpose of this PR a little clearer.

done

**Review by iuioiua — APPROVED** [review]
LGTM. I notice that `parseRangeString()` below uses `parseComparator()`. Has that been left out deliberately too?

**Comment by timreichen** [comment]
> LGTM. I notice that `parseRangeString()` below uses `parseComparator()`. Has that been left out deliberately too?

Yes, because if `OPERATOR_XRANGE_REGEXP` does not match, it needs to be matched with `COMPARATOR_REGEXP`. Maybe we can try to combine these two regexps in a future PR.

**Pull request merged**
