### PR TITLE
chore(node): update compat layer to node 18.8.0

### PR DESCRIPTION
**Pull request by cjihrig**
Node 18 will be LTS soon. Let's see what tests fail in the update.

### CODE REVIEW

**Comment by cjihrig** [comment]
The CI is hanging because of https://github.com/denoland/deno_std/issues/2596. I worked around it locally. Here are the 29 failing tests on my machine (note that a few of these are resolved by #2584):

```
parallel/test-assert-async.js
parallel/test-assert-fail.js
parallel/test-dns-promises-exists.js
parallel/test-dns-resolvens-typeerror.js
parallel/test-events-once.js
parallel/test-eventtarget-brandcheck.js
parallel/test-fs-access.js
parallel/test-fs-append-file-sync.js
parallel/test-fs-copyfile.js
parallel/test-fs-rm.js
parallel/test-fs-write-file-sync.js
parallel/test-http-agent-getname.js
parallel/test-net-local-address-port.js
parallel/test-net-remote-address-port.js
parallel/test-readline-csi.js
parallel/test-stream-duplex-destroy.js
parallel/test-stream-duplex-from.js
parallel/test-stream-duplex.js
parallel/test-stream-readable-aborted.js
parallel/test-stream-readable-destroy.js
parallel/test-stream-readable-didRead.js
parallel/test-stream-readable-pause-and-resume.js
parallel/test-stream-readable-with-unimplemented-_read.js
parallel/test-stream-transform-destroy.js
parallel/test-stream-writable-destroy.js
parallel/test-stream-writable-end-cb-error.js
parallel/test-stream-writable-finish-destroyed.js
parallel/test-streams-highwatermark.js
parallel/test-webcrypto-sign-verify.js
```

**Comment by cjihrig** [comment]
After some fixes and landing https://github.com/denoland/deno_std/pull/2584, this is the list of current failures:

```
parallel/test-assert-fail.js
parallel/test-dns-promises-exists.js
parallel/test-eventtarget-brandcheck.js
parallel/test-net-local-address-port.js --> https://github.com/denoland/deno_std/issues/2596
parallel/test-stream-duplex.js
parallel/test-webcrypto-sign-verify.js --> Deno needs to support Ed25519
```

**Review by kt3k — APPROVED** [review]
Awesome work! LGTM

**Review by bartlomieju — APPROVED** [review]
LGTM too, massive effort. Thank you @cjihrig!

**Pull request merged**
