### PR TITLE
BREAKING(io): deprecate io top level module

### LINKED ISSUE #3552: Deprecate `io` module
APIs in `io` are based on the legacy Reader/Writer interfaces. We should deprecate `io` before stabilizing std.

part of #3489

### PR DESCRIPTION
**Pull request by lino-levan**
Closes #3552.

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM. Thanks!

**Comment by kt3k** [comment]
I'll let this open for a while to see if there's any concern/objection to this

**Comment by iuioiua** [comment]
The `yaml`, `archive`, `log` and `streams` modules depend on this module. I think it's important that this PR includes moving these modules using web streams instead of `io`. It'll also validate the deprecation itself.

**Comment by kt3k** [comment]
- `yaml` now doesn't depend on `io` https://github.com/denoland/deno_std/pull/3586
- `io`-dependent APIs of `streams` are now deprecated https://github.com/denoland/deno_std/pull/3640
- `log` and `archive` will remain unstable [ref](https://github.com/denoland/deno_std/issues/3489#issuecomment-1702521412)

I think `io` is now ready to be deprecated

**Comment by KaKi87** [comment]
Hello,
The MDN link doesn't say concretely what to replace `readLines()` with for reading a file line by line like in the following code :
```js
const file = await Deno.open(filePath, { read: true });
for await (const line of readLines(file)){
    console.log(line);
}
await file.close();
```
Help ?
Thanks

**Comment by kt3k** [comment]
You should use `file.readable`, `TextDecoderStream`, and `TextLineStream` to read lines from a file.

```ts
import { TextLineStream } from "https://deno.land/std@0.214.0/streams/mod.ts";
const file = await Deno.open(filePath, { read: true });
const lines = file.readable
  .pipeThrough(new TextDecoderStream())
  .pipeThrough(new TextLineStream());
for await (const line of lines) {
  console.log(line);
}
```

**Pull request merged**
