### PR TITLE
feat(yaml): add tests for `foldLine()`

### PR DESCRIPTION
**Pull request by timreichen**

### CODE REVIEW

**Review by iuioiua — CHANGES_REQUESTED** [review]
Again, can we please test this functionality by testing `stringify()`? And again, great work so far. Thank you.

**Comment by timreichen** [comment]
> Again, can we please test this functionality by testing `stringify()`? And again, great work so far. Thank you.

I think we should test separate functions like in toml with combinators. Tests can be more on point no?

**Comment by iuioiua** [comment]
We should test functions how users would use them. It guarentees not just that that underlying functionality works, but that said functionality is plumbed correctly.

**Comment by timreichen** [comment]
Closing in favour of already merged tests

**Pull request closed without merging**
