### PR TITLE
refactor: mark modules as browser compatible

### PR DESCRIPTION
**Pull request by jsejcksn**
These modules are useful in browser environments.

### CODE REVIEW

**Comment by jsejcksn** [comment]
Are there even more that can be included in this PR?

**Comment by crowlKats** [comment]
@jsejcksn 
`streams/merge.ts`
`async/deferred.ts`

**Comment by jsejcksn** [comment]
> `streams/merge.ts`

@crowlKats It appears that the `asyncIterator` prevents compat for that module:

```
% deno cache --config ./browser-compat.tsconfig.json streams/merge.ts
Check file:///deno_std/streams/merge.ts
error: TS2504 [ERROR]: Type 'ReadableStream<T>' must have a '[Symbol.asyncIterator]()' method that returns an async iterator.
            for await (const data of stream) {
                                     ~~~~~~
    at file:///deno_std/streams/merge.ts:22:38
```

**Comment by crowlKats** [comment]
Then TS' typings are outdated. async iter on readablestream is part of spec

**Comment by jsejcksn** [comment]
> Then TS' typings are outdated. async iter on readablestream is part of spec

@crowlKats I understand and agree, but the tests still fail and prevent inclusion until TS updates its DOM types.

**Comment by crowlKats** [comment]
Oh well, then we can skip on that for now

**Comment by jsejcksn** [comment]
The same TS typings problem exists for uuid v4:

```
% deno cache --config ./browser-compat.tsconfig.json uuid/mod.ts
Check file:///deno_std/uuid/mod.ts
error: TS2339 [ERROR]: Property 'randomUUID' does not exist on type 'Crypto'.
  return crypto.randomUUID();
                ~~~~~~~~~~
    at file:///deno_std/uuid/v4.ts:30:17
```

**Comment by jsejcksn** [comment]
This PR turned out to be a bit bigger than I initially anticipated. Please review and let me know if I overlooked anything: thanks!

**Review by kt3k — APPROVED** [review]
Oh, we have many compatible modules! Nice work! @jsejcksn

**Comment by jsejcksn** [comment]
@crowlKats Is there a "todo" list in this repo's files/issues/etc. where the outdated DOM types issues mentioned above can be noted for revisiting after a future update to the TS DOM lib?

**Comment by kt3k** [comment]
@jsejcksn I don't think we have such issue

**Comment by jsejcksn** [comment]
@kt3k Can one be created? (perhaps using the [projects](https://github.com/denoland/deno_std/projects) or [wiki](https://github.com/denoland/deno_std/wiki) features if an issue is not appropriate)

**Comment by kt3k** [comment]
@jsejcksn I think issue is the best for tracking it. Would you mind creating one?

**Comment by jsejcksn** [comment]
> I think issue is the best for tracking it. Would you mind creating one?

@kt3k Done

**Comment by kt3k** [comment]
@jsejcksn Thanks! Nice!

**Comment by kt3k** [comment]
Modified the above issue a little bit, and made the remaining items into todo list (in github md notation). Feel free to edit them if you find any new items

**Comment by jsejcksn** [comment]
@kt3k I updated it again to sort at the top level by incompatible types, with affected modules listed under each, including links to the latest relevant lines in the TS DOM lib files.

**Pull request merged**
