### PR TITLE
refactor(semver): remove `ltr()` and `gtr()` `outside()` dependency

### PR DESCRIPTION
**Pull request by timreichen**
- removes the dependency of `outside()` from `ltr()` and `gtr()` and replaces them with simple comparisons. They are easy enough to understand.

### CODE REVIEW

**Comment by iuioiua** [comment]
To clarify, it appears we're swapping from one set of dependencies for another here. There's a tiny reduction in overall code size, which correlates with a tiny reduction in logic. The code LGTM but I wonder whether this affects behaviour in any non-apparent way. Either way, I'll let Yoshiya review this one.

Before:

```
asher@Ashers-MacBook-Air deno_std % deno info semver/gtr.ts
local: /Users/asher/GitHub/deno_std/semver/gtr.ts
emit: /Users/asher/Library/Caches/deno/gen/file/Users/asher/GitHub/deno_std/semver/gtr.ts.js
type: TypeScript
dependencies: 14 unique
size: 22.54KB
```

```
asher@Ashers-MacBook-Air deno_std % deno info semver/ltr.ts
local: /Users/asher/GitHub/deno_std/semver/ltr.ts
emit: /Users/asher/Library/Caches/deno/gen/file/Users/asher/GitHub/deno_std/semver/ltr.ts.js
type: TypeScript
dependencies: 14 unique
size: 22.49KB
```

After:

```
asher@Ashers-MacBook-Air deno_std % deno info semver/gtr.ts
local: /Users/asher/GitHub/deno_std/semver/gtr.ts
emit: /Users/asher/Library/Caches/deno/gen/file/Users/asher/GitHub/deno_std/semver/gtr.ts.js
type: TypeScript
dependencies: 14 unique
size: 21.14KB
```

```
asher@Ashers-MacBook-Air deno_std % deno info semver/ltr.ts
local: /Users/asher/GitHub/deno_std/semver/ltr.ts
emit: /Users/asher/Library/Caches/deno/gen/file/Users/asher/GitHub/deno_std/semver/ltr.ts.js
type: TypeScript
dependencies: 15 unique
size: 21.35KB
```

**Comment by timreichen** [comment]
> To clarify, it appears we're swapping from one set of dependencies for another here. There's a tiny reduction in overall code size, which correlates with a tiny reduction in logic. The code LGTM but I wonder whether this affects behaviour in any non-apparent way. Either way, I'll let Yoshiya review this one.
> 
> Before:
> 
> ```
> asher@Ashers-MacBook-Air deno_std % deno info semver/gtr.ts
> local: /Users/asher/GitHub/deno_std/semver/gtr.ts
> emit: /Users/asher/Library/Caches/deno/gen/file/Users/asher/GitHub/deno_std/semver/gtr.ts.js
> type: TypeScript
> dependencies: 14 unique
> size: 22.54KB
> ```
> 
>  ```
> asher@Ashers-MacBook-Air deno_std % deno info semver/ltr.ts
> local: /Users/asher/GitHub/deno_std/semver/ltr.ts
> emit: /Users/asher/Library/Caches/deno/gen/file/Users/asher/GitHub/deno_std/semver/ltr.ts.js
> type: TypeScript
> dependencies: 14 unique
> size: 22.49KB
> ```
> 
> After:
> 
> ```
> asher@Ashers-MacBook-Air deno_std % deno info semver/gtr.ts
> local: /Users/asher/GitHub/deno_std/semver/gtr.ts
> emit: /Users/asher/Library/Caches/deno/gen/file/Users/asher/GitHub/deno_std/semver/gtr.ts.js
> type: TypeScript
> dependencies: 14 unique
> size: 21.14KB
> ```
> 
>  ```
> asher@Ashers-MacBook-Air deno_std % deno info semver/ltr.ts
> local: /Users/asher/GitHub/deno_std/semver/ltr.ts
> emit: /Users/asher/Library/Caches/deno/gen/file/Users/asher/GitHub/deno_std/semver/ltr.ts.js
> type: TypeScript
> dependencies: 15 unique
> size: 21.35KB
> ```

Ok. To be honest, I don't see the point of having `outside()` at all since the result is `!testRange()` or when `hilo` is passed, turns into `ltr` or `gtr`. So my thought was to have these two functions be independent in preparation of a possible `outside()` deprecation.

**Comment by iuioiua** [comment]
Is `outside()` **exactly** the same as `!testRange()`?

**Comment by timreichen** [comment]
> Is `outside()` **exactly** the same as `!testRange()`?

It will be if https://github.com/denoland/deno_std/issues/3948#issuecomment-1876875415 is actually bug and https://github.com/denoland/deno_std/pull/4095 is merged.

**Comment by iuioiua** [comment]
I see. In that case, I'm for the deprecation of `outside()`. Let me discuss this with Yoshiya first.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
