### PR TITLE
Do not automatically run tests

### PR DESCRIPTION
**Pull request by ry**
cc @hayd

### CODE REVIEW

**Comment by hayd** [comment]
I don't like this, you're losing some really nice behavior here. I think a better way forward is:

- add a `testing/main.ts` (that was part of #108)
- wire it to `deno test`
- remove the auto runTests (perhaps have it throw an exception if not cancelled).

At the moment it's neat that you can run `deno test.ts` and `deno testing/test.ts` etc and both will work as expected. That's a great feature.

**Comment by ry** [comment]
@hayd Try executing file_server.ts on the current master - there's a bug - note what is printed on the last line::
```
~/src/deno_std> file_server
HTTP server listening on http://0.0.0.0:4500/
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
This is caused by:
https://github.com/denoland/deno_std/blob/4283c26b8930ca80e5babca3337b5431f16334d0/io/bufio.ts#L8

Having the test runner run automatically is not very explicit and leads to problems like this:

**Comment by ry** [comment]
@hayd I've added a basic `testing/main.ts` - does this work for you?

**Comment by hayd** [comment]
whelp, that sure is a bug! Wow.

I was imagining `deno testing/main.ts test.ts` would be the way to call it (like in #108).

**Comment by ry** [comment]
> I was imagining deno testing/main.ts test.ts would be the way to call it (like in #108).

Actually I was thinking something more powerful `deno testing/main.ts` would do something like `find . | egrep "_test.(js|ts)$"` and then figure out the list of permissions, and then start a number of deno subprocesses for each set of permissions (like we do in deno's test runner)

**Comment by hayd** [comment]
The problem I had when doing this, after ESM, was `import()` no longer works (you want import() each file after the find/grep then runTests).

Also, you can add a --grep arg fairly easily to filter tests by name.

**Comment by ry** [comment]
@hayd good point. dynamic import coming soon..

**Comment by piscisaureus** [comment]
There's a better solution for the issue this is intended tot fix: when the test() function gets called to register a test, *clear* the current timeout and schedule a new one.

**Comment by piscisaureus** [comment]
EDIT oops misunderstood. New comment:

There's a better solution for the issue this is intended tot fix.
Call setTimeout the first time test() is called to register a test.

**Comment by piscisaureus** [comment]
Discussed off github: we'll land this now to fix the bug in file_server. We'll add something like `runIfMain(imports.meta)` to the test harness so running tests from individual test.ts files will still be possible.

**Comment by ry** [comment]
Added an issue for this https://github.com/denoland/deno_std/issues/152

**Comment by hayd** [comment]
See #160.

**Pull request merged**
