### PR TITLE
fs.walk performance improvement

### PR DESCRIPTION
**Pull request by zekth**
In fs.walk there is 2 loops with `for of` which is known to be slower than the classic `for` loop.
https://github.com/denoland/deno_std/blob/master/fs/walk.ts#L34
https://github.com/denoland/deno_std/blob/master/fs/walk.ts#L74
For example this snippet:
```javascript
const NS_PER_SEC = 1e9;
var t = [];
for (var i = 0; i < 5000; i++) {
    t.push(Math.floor(Math.random() * Math.floor(666)))
}
var start = process.hrtime();
for (let f of t) {
  if (true) {
    continue;
  }
}

var diff = process.hrtime(start);
console.log(`Benchmark took ${diff[0] * NS_PER_SEC + diff[1]} nanoseconds`);

var start2 = process.hrtime();
for (var i = 0; i < t.length; i++) {
  var f = t[i];
  if (true) {
    continue;
  }
}

var diff2 = process.hrtime(start2);
console.log(`Benchmark took ${diff2[0] * NS_PER_SEC + diff2[1]} nanoseconds`);

var start3 = process.hrtime();
for (var i = t.length-1; i >= 0; i--) {
  var f = t[i];
  if (true) {
    continue;
  }
}

var diff3 = process.hrtime(start3);
console.log(`Benchmark took ${diff3[0] * NS_PER_SEC + diff3[1]} nanoseconds`);
```

outputs:
```
Benchmark took 343077 nanoseconds
Benchmark took 230644 nanoseconds
Benchmark took 176871 nanoseconds
```

So if the walker is used on watch event or on big nested folders this is a little optimization.

### CODE REVIEW

**Comment by hayd** [comment]
wild.

you can also pull out the length lookup:

```
const length = t.length
for (let i = 0; i < length; i++) {
  let f = t[i];
  if (true) {
    continue;
  }
}
```
so we're still iterating forward.

**Comment by zekth** [comment]
> wild.
> 
> you can also pull out the length lookup:
> 
> ```
> const length = t.length
> for (let i = 0; i < length; i++) {
>   let f = t[i];
>   if (true) {
>     continue;
>   }
> }
> ```
> so we're still iterating forward.

i've tried and the results are strange:
```javascript
var l = t.length -1
var start4 = process.hrtime();
for (var i = l; i >= 0; i--) {
  var f = t[i];
  if (true) {
    continue;
  }
}

var diff4 = process.hrtime(start4);
console.log(`Benchmark took ${diff4[0] * NS_PER_SEC + diff4[1]} nanoseconds`);
```

```
Benchmark took 809954 nanoseconds
Benchmark took 146625 nanoseconds
Benchmark took 126683 nanoseconds
Benchmark took 103517 nanoseconds
```
```
Benchmark took 733709 nanoseconds
Benchmark took 107915 nanoseconds
Benchmark took 89147 nanoseconds
Benchmark took 102343 nanoseconds
```
```
Benchmark took 787373 nanoseconds
Benchmark took 107916 nanoseconds
Benchmark took 91787 nanoseconds
Benchmark took 99998 nanoseconds
```

Sometimes it's slower, sometimes faster. Do you want be to add this line too?

**Comment by hayd** [comment]
iterating backwards it makes no difference, it's pulling it out of the conditional.
walk should iterate forwards.

**Comment by ry** [comment]
I will wait for @hayd's review approval

**Comment by hayd** [comment]
lgtm 👍

**Pull request merged**
