### PR TITLE
chore(http/file_server): add module documentation

### PR DESCRIPTION
**Pull request by ayame113**
part of #3361

### CODE REVIEW

**Review by lino-levan — APPROVED** [review]
LGTM

**Comment by ayame113** [comment]
Unfortunately I think I ran into a bug in the deno doc. https://github.com/denoland/deno_doc/issues/336

**Comment by lino-levan** [comment]
Please `deno fmt`

**Comment by ayame113** [comment]
@lino-levan CI failure is related to #3373

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
