### PR TITLE
fix(toml): `parse()` duplicates the character next to reserved escape sequences

### PR DESCRIPTION
**Pull request by babiabeo**
Fix: #4187

### CODE REVIEW

**Comment by kt3k** [comment]
> There are 2 cases that I expected:
> 
> * Ignores the reserved escape sequence:
> 
> ```ts
> parse('a = "a\\0b"'); // { a: "ab" }
> ```
> 
> * Throws an error as specified in the spec:
> 

@babiabeo 
Do you think ignoring is more useful than throwing?

**Comment by iuioiua** [comment]
I think we should stick to the spec and throw.

**Comment by babiabeo** [comment]
> > There are 2 cases that I expected:
> > 
> > * Ignores the reserved escape sequence:
> > 
> > ```ts
> > parse('a = "a\\0b"'); // { a: "ab" }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Throws an error as specified in the spec:
> 
> @babiabeo Do you think ignoring is more useful than throwing?

Currently, this PR solves the issue by ignoring reserved escape sequences.

However, I see that most TOML parser packages throw an error in this case

- [`js-toml`](https://www.npmjs.com/package/js-toml)
```ts
import { load } from "npm:js-toml";

console.log(load('a = "a\\0b"'));

// error: Uncaught (in promise) SyntaxParseError: Syntax error
// unexpected character: ->"<- at offset: 4, skipped 3 characters.
// unexpected character: ->b<- at offset: 8, skipped 2 characters.
```

- [`tomllib`](https://docs.python.org/3/library/tomllib.html)
```py
import tomllib

print(tomllib.loads('a = "a\\0b"'))

# File "D:\coding\programming\languages\python\Lib\tomllib\_parser.py", line 494, in parse_basic_str_escape
#     raise suffixed_err(src, pos, "Unescaped '\\' in a string") from None
# tomllib.TOMLDecodeError: Unescaped '\' in a string (at line 1, column 9)
```

- [Go `toml`](https://pkg.go.dev/github.com/BurntSushi/toml)
```go
package main

import (
	"fmt"

	"github.com/BurntSushi/toml"
)

type Data struct {
    A string `toml:"a"`
}

func main() {
    var data Data
    _, err := toml.Decode("a = \"a\\0b\"", &data)

    fmt.Println(err)

    // toml: line 1 (last key "a"): invalid escape in string '\0'
}
```

**Review by iuioiua — CHANGES_REQUESTED** [review]
I think it best if we instead threw instead of ignoring, as to follow the spec. Are you able to rework this PR to do that?

**Review by iuioiua — COMMENTED** [review]
@babiabeo, I've made some tweaks to improve the thrown error message and accuracy of the tests. Do these changes seem reasonable to you?

**Comment by babiabeo** [comment]
> @babiabeo, I've made some tweaks to improve the thrown error message and accuracy of the tests. Do these changes seem reasonable to you?

Yes. I forgot to add `\\`. Thanks for adding it!

**Review by iuioiua — APPROVED** [review]
LGTM! Thank you, David.

**Pull request merged**
