### PR TITLE
chore(hash): remove `std/hash`

### PR DESCRIPTION
**Pull request by iuioiua**

### CODE REVIEW

**Comment by kt3k** [comment]
It seems there's some controversy about this deprecation. (The deprecation itself might have been wrong).

When we deprecated `std/hash`, we overlooked the lack of streaming capability of `std/crypto` while `std/hash` support it. I think it's safe to keep `std/hash` as is until stream support is added to Web Crypto API and `std/crypto`. (The stream support of Web Crypto API is being discussed in [this repo](https://github.com/wintercg/proposal-webcrypto-streams).)

**Comment by kt3k** [comment]
We probably need some clarification about the situation in `hash/README.md`

**Comment by iuioiua** [comment]
Yes, agreed. Is it worth instead only deprecating parts of `std/hash` that overlap with `std/crypto`?

**Comment by cjihrig** [comment]
> Is it worth instead only deprecating parts of std/hash that overlap with std/crypto? This would involve keeping streaming compatibilities.

Is DX likely to suffer if there was a partial deprecation and people needed to use both?

**Comment by iuioiua** [comment]
> Is DX likely to suffer if there was a partial deprecation and people needed to use both?

Yes, I think so. I think it'd be better to deprecate any functionality that overlaps with `std/crypto` and move streams functionality to a new `std/crypto/stream` or similar.

The current need for streams functionality is enough to justify closing this PR. I'll open an issue and we can see what can be done about `std/crypto` and `std/hash`.

**Pull request closed without merging**
