### PR TITLE
BREAKING(testing): Renaming assertThrowsAsync to assertRejects

### PR DESCRIPTION
**Pull request by getspooky**
The name `assertThrowsAsync` is overly long and verbose, yet it doesn't describe what it actually asserts which is that a promise rejects. Rename `assertThrowsAsync` -> `assertRejects`.

Please see: https://github.com/denoland/deno_std/issues/1073

### CODE REVIEW

**Review by caspervonb — COMMENTED** [review]
You'd have to apply this to all modules in the entire std library for the tests to pass.

But this hasn't been discussed yet, as you can see in the unlabelled issue you linked.

Probably the way we'd want to go forward is to keep exporting the old alias with deprecated annotations for a couple of releases as this is used a lot on the wild, including in CLI unit tests.

**Review by bartlomieju — CHANGES_REQUESTED** [review]
I agree with Casper, also I'd suggest to replace all usages of `assertThrowsAsync` in the code in this PR

**Review by kt3k — APPROVED** [review]
LGTM

**Review by bartlomieju — APPROVED** [review]

**Review by caspervonb — APPROVED** [review]

**Comment by kt3k** [comment]
@getspooky Thank you for your contribution!

@caspervonb Thank you for the original suggestion!

**Pull request merged**
