### PR TITLE
feat(crypto): `toHashString` utility

### PR DESCRIPTION
**Pull request by iuioiua**
This is to be the `std/crypto` version of `Hasher.toString` from `std/hash`. The aim of this function is to contribute to the deprecation of `std/hash`, as part of #2733.

### CODE REVIEW

**Comment by iuioiua** [comment]
Are there any concerns with this PR, @kt3k?

**Comment by kt3k** [comment]
@iuioiua Sorry for the delay in review. (We, most core team members, were on the offsite meeting last week, and were a bit busy on it..)

This utility makes sense to me as most users probably want to use string representation of the digest results. The default encoding ('hex') also looks good to me.

Does anyone have any concern on adding this util to `crypto/mod.ts`?

**Comment by iuioiua** [comment]
The failing test is unrelated to this change.

**Comment by iuioiua** [comment]
Gently pinging @bartlomieju and @cjihrig.

**Review by cjihrig — APPROVED** [review]
No objections. LGTM

**Review by kt3k — APPROVED** [review]
LGTM. Nice utility to have!

**Pull request merged**
