### PR TITLE
Add xeval

### PR DESCRIPTION
**Pull request by nayeemrmn**
Experimenting with moving `deno xeval` here.
CC @bartlomieju @kevinkassimo

### CODE REVIEW

**Comment by kevinkassimo** [comment]
It is embarrassing, but I have to admit I just spot a bug with the `chunks` implementation I did before... The multi-char delimiter matching is throwing away incorrect parts, resulting in things like `!DEDELIM!DELIM!` incorrectly delimited with `-d 'DELIM'` set...

**Comment by bartlomieju** [comment]
@kevinkassimo maybe it's worth fixing the problem in this PR? IMHO it makes sense to move `xeval` to deno_std

**Comment by kevinkassimo** [comment]
@bartlomieju I had a PR fixing the behavior in the deno repo. I’ll wait for it to be reviewed and see we can completely move it here

**Comment by kevinkassimo** [comment]
I was also thinking if we should move `chunks` to `io/`? Since it takes a `Reader` interface and might be also useful in other scenarios.

**Comment by bartlomieju** [comment]
> I was also thinking if we should move `chunks` to `io/`? Since it takes a `Reader` interface and might be also useful in other scenarios.

Yes that makes sense, I'd also suggest adding `lines` function that is an alias for `chunks` - it's been requested many times.

**Comment by nayeemrmn** [comment]
Well it behaves like `String::split()` but for `Reader`s. I would call it `readAndSplit()` or maybe even just `split()`. `chunks()` is vague.

**Comment by kevinkassimo** [comment]
@Narendra-Kamath I like the idea of including `split` in the name, but `readAndSplit` sounds a bit too long? Maybe `readSplit()` or `readDelim()` (align with `readLine`)? Also we can add a `maxSplit` property to it, such that `readSplit(reader, "\n", { maxSplit: 2 })` will yield at most 2 strings.

Also we might want to distinguish `async function* readSplit(r: Reader, delim: Uint8Array): AsyncIterableIterator<Uint8Array>` and `readStrSplit(r: Reader, delim: string): AsyncIterableIterator<string>`. (This change should be quite simple)

Also I noticed https://github.com/denoland/deno_std/blob/master/io/readers.ts . We can maybe also implement a `DelimitedReader`

**Comment by nayeemrmn** [comment]
> distinguish `async function* readSplit(r: Reader, delim: Uint8Array): AsyncIterableIterator<Uint8Array>` and `readStrSplit(r: Reader, delim: string): AsyncIterableIterator<string>`.

Yeah. Most accurately it reads, decodes to string and splits. `readStrSplit()` checks every box.

**Comment by bartlomieju** [comment]
> Also I noticed https://github.com/denoland/deno_std/blob/master/io/readers.ts . We can maybe also implement a `DelimitedReader`

:+1: additionally Rust has `lines` method implemented on `BufReader` - I believe we should replicate this function on Deno's `BufReader`

As for the renaming of `chunks` I'd suggest `readDelimitedChunks`.

@nayeemrmn can you update the PR? There are a few issues waiting on this functionality :)

**Comment by nayeemrmn** [comment]
@bartlomieju I think moving `chunks()` should be a separate PR. It would get merged a lot sooner and I can rebase this one. @kevinkassimo?

**Comment by kevinkassimo** [comment]
I'm fine with landing this first (as long as we don't expose `chunks` or equivalent here)

**Comment by bartlomieju** [comment]
@ry please review

**Pull request merged**
