### PR TITLE
0.161.0

### PR DESCRIPTION
**Pull request by denobot**
Bumped version for 0.161.0

Please ensure:
- [x] Version in version.ts is updated correctly
- [x] Releases.md is updated correctly
- [x] All the tests in this branch have been run against the CLI release being done (`../deno/target/release/deno task test && ../deno/target/release/deno task node:unit && ../deno/target/release/deno task node:test`)

To make edits to this PR:
```shell
git fetch upstream release_0_161.0 && git checkout -b release_0_161.0 upstream/release_0_161.0
```

cc @bartlomieju

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]

**Comment by BayoKwendo** [comment]
Hi you have messed us up with realising and delete version 0.161.0

Warning Implicitly using latest version (0.161.0) for https://deno.land/std/hash/mod.ts
error: Module not found "https://deno.land/std/hash/mod.ts".
    at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:2

**Comment by iuioiua** [comment]
This is a perfect example of why Deno recommends that you specify a module version. Implicitly importing the latest version of a module runs the risk of inheriting breaking changes. Below is from https://deno.land/x Q & A:

> ## I am getting a warning when importing from deno.land/x!
> deno.land/x warns you when you implicitly import the latest version of a module (when you do not explicitly specify a version). This is because it can [be unsafe to not tag dependencies](https://github.com/denoland/dotland/issues/997). To get rid of the warning, explicitly specify a version.

Also, `std/hash` has been deprecated in favour of `std/crytpo` since #1350. In other words, it's been deprecated for over a year. That's more than plenty of time to readjust your code.

The good thing is, whatever functionality you were previously using `std/hash` for should exist in `std/crypto`. Check out `std/crypto` for said functionality and if you can't find it, raise a PR, and someone can surely help.

**Comment by kt3k** [comment]
@BayoKwendo Can you update `god_crypto` to the latest version? The latest `god_crypto` doesn't use non-versioned `std/hash` and it doesn't have the above problem.

**Comment by kt3k** [comment]
hmm `x/mysql` seems broken due to the dependency to a very old (0.2.0) version of `god_crypto`, which depends on non-versioned `std/hash`.

https://github.com/denodrivers/mysql/issues/131 (suggested PR: https://github.com/denodrivers/mysql/pull/132 )

**Comment by kt3k** [comment]
@BayoKwendo if you use `deno.land/x/mysql`, then please add the following entry to your import map as a temporary fix:

```
{
  "imports": {
    "https://deno.land/std/hash/mod.ts": "https://deno.land/std@0.160.0/hash/mod.ts"
  }
}
```

**Comment by kt3k** [comment]
You can specifiy import_map's path in `deno.json`

```json
{
  "importMap": "./import_map.json"
}
```

but it's not absolutely necessary. You can also specify it via `--import-map import_map.json` CLI option

**Comment by BayoKwendo** [comment]
thank you @kt3k , mysql was the one messing me up,  i have struggled trying to figure out what was the issue could be. Thank you

**Comment by kt3k** [comment]
You're welcome. BTW now the mysql fixed the issue ( https://github.com/denodrivers/mysql/pull/132 ). Upgrading it to the latest (v2.10.3) also should fix the issue.

**Pull request merged**
