### PR TITLE
test(crypto): test `ReadableStream` in `digest`

### PR DESCRIPTION
**Pull request by iuioiua**
I'm neither an expert on the Stream nor Web Crypto APIs, so please let me know of any concerns. Testing is basic for now but can be expanded if needed.

Part of #2733.

### CODE REVIEW

**Comment by kt3k** [comment]
(Sorry for the delay in review. We were busy last week)

Oh, we already support `AsyncIterable<BufferSource>` source.. (That makes readable stream input automatically working..) I wasn't fully aware of it..

**Comment by littledivy** [comment]
Maybe we should wait for https://github.com/wintercg/proposal-webcrypto-streams?

**Comment by kt3k** [comment]
`std/crypto` seems deviating from web crypto from the beginning. ref. https://github.com/denoland/deno_std/pull/1025

And because it supports `AsyncIterable<BufferSource>` as input, the readable stream seems already supported

**Comment by kt3k** [comment]
I think this change is unnecessary and my previous comment (`std/crypto` doesn't support streaming) was wrong. I think we can just deprecate & remove `std/hash` now.

**Comment by iuioiua** [comment]
> I think this change is unnecessary and my previous comment (`std/crypto` doesn't support streaming) was wrong. I think we can just deprecate & remove `std/hash` now.

I'll tweak this PR so it just provides tests for digesting streams instead.

**Review by kt3k — APPROVED** [review]
LGTM 👍

**Pull request merged**
