### PR TITLE
feat(perf_hooks): add basic node perf_hooks module

### PR DESCRIPTION
**Pull request by douglasduteil**
see https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_measurement_apis

### CODE REVIEW

**Comment by kt3k** [comment]
@douglasduteil Thank you for your contribution! The change looks good to me. Could you run the formatter (`deno fmt`) to the added scripts?

**Comment by getspooky** [comment]
@domharrington  Please run `deno --unstable lint`

**Comment by douglasduteil** [comment]
Done @kt3k @getspooky :)

**Review by kt3k — APPROVED** [review]
@douglasduteil LGTM. Thank you for your contribution!

**Pull request merged**
