### PR TITLE
refactor: rename underscore packages to hyphens

### PR DESCRIPTION
**Pull request by crowlKats**
needs to add backwards compatible packages

### CODE REVIEW

**Comment by timreichen** [comment]
Was this discussed somewhere?

**Comment by crowlKats** [comment]
@timreichen jsr changed its naming policy to use hyphens instead of underscores.

**Comment by kt3k** [comment]
How about doing these renames in `_tools/convert_to_workspace.ts`? That will only affects jsr version of the standard library.

**Comment by timreichen** [comment]
That is strange. Is there an issue you can link to about why that change was made? Using hyphens instead of underscores directly violates the [deno style guide](https://docs.deno.com/runtime/manual/references/contributing/style_guide#use-underscores-not-dashes-in-filenames).

**Comment by cknight** [comment]
> Was this discussed somewhere?

See https://discord.com/channels/684898665143206084/1203185670508515399/1206693236425490483

**Comment by iuioiua** [comment]
Closing as this has been superseded by #4357.

**Pull request closed without merging**
