### PR TITLE
chore(node): upgrade `denoflate` to 2.0.2 for setup script

### PR DESCRIPTION
**Pull request by iuioiua**
`node/_tools/TODO.md` was also updated as a side effect.

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
BTW should we number the remaining test list? Because all lines are numbered, the change in the middle of the list causes the large diff like this.

**Comment by iuioiua** [comment]
> BTW should we number the remaining test list? Because all lines are numbered, the change in the middle of the list causes the large diff like this.

Yes, good point. Will do.

**Comment by kt3k** [comment]
Thanks!

**Pull request merged**
