### PR TITLE
Allow for asserting throws on async methods 

### PR DESCRIPTION
**Pull request by mcgear**
We ran into a use case where we need to be able to assert throws from an async function. I was unable to figure out how to do this with existing assert throws, so added this implementation.

### CODE REVIEW

**Comment by aapoalas** [comment]
You're probably looking for `assertRejects`

**Comment by iuioiua** [comment]
Aapo is right. See https://deno.land/std/assert/mod.ts?s=assertRejects

Perhaps we should mention the related asynchronous or synchronous function in each of the functions JSDocs. This isn't the first time someone hasn't realised one of these assertion functions exists.

**Comment by iuioiua** [comment]
@mcgear, please see the comments above.

**Comment by kt3k** [comment]
> Perhaps we should mention the related asynchronous or synchronous function in each of the functions JSDocs. This isn't the first time someone hasn't realised one of these assertion functions exists.

Sounds good. Let's mention `assertRejects` in the doc of `assertThrows`

**Comment by mcgear** [comment]
This seems to have worked just fine, closing the PR.

**Pull request closed without merging**
