### PR TITLE
collections: Use function overloading

### PR DESCRIPTION
**Pull request by majidsajadi**
This PR add typescript function overloading to 'maxBy', 'sortBy', 'minBy'

### CODE REVIEW

**Comment by LionC** [comment]
Nice! Why don't we add the other natively comparable types to the functions they are missing from too while we are at it? Would you be fine with adding them?

**Comment by majidsajadi** [comment]
> natively comparable types

@LionC yes. I would work on them also. which functions?

**Comment by kt3k** [comment]
`sort_by_test.ts` seems causing type errors in CI. Can you address these as well? @majidsajadi

**Comment by LionC** [comment]
> > natively comparable types
> 
> @LionC yes. I would work on them also. which functions?

All functions that do `max` or `min` should work with all the types `sortBy` works with I think.

**Comment by majidsajadi** [comment]
@kt3k Updated

**Review by kt3k — APPROVED** [review]
@majidsajadi Thanks! Nice work!

LGTM

**Pull request merged**
