### PR TITLE
feat(fmt/case): Add casing helpers

### PR DESCRIPTION
**Pull request by Gustrb**
This PR implements a few casing helpers, as were asked in the issue #3125 
It adds a few helpers methods such as:
- toPascalCase
- toCamelCase
- toSnakeCase
- toScreamingSnakeCase
- toKebabCase
- toTitleCase

Any suggestions on more methods would be appreciated, I've just implemented the ones I could find any use for

### CODE REVIEW

**Comment by aapoalas** [comment]
Title case maybe?

**Comment by timreichen** [comment]
I think it would make more sense to have an implementation that doesn't just split by whitespaces but also other separators and by words so a case can be applied to another like in [lodash](https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L14139).
Example:
```ts
toKebabCase('Foo Bar') // => 'foo-bar'
toKebabCase('fooBar') // => 'foo-bar'
toKebabCase('__FOO_BAR__') // => 'foo-bar'
```

**Comment by Gustrb** [comment]
@timreichen true, it would make a lot more sense, I'll take a look at their implementation then :)

**Comment by guy-borderless** [comment]
toSentenceCase

**Comment by iuioiua** [comment]
Closing this in favour of #4082, which continues the work started here. Thank you for your contribution, @Gustrb!

**Pull request closed without merging**
