### PR TITLE
feat(testing): assertMatch function support string as param

### PR DESCRIPTION
**Pull request by getspooky**
`assertMatch` accepts a string, which it will try to match:
```ts
assertMatch("foobar@deno.com", "deno.com");
```

### CODE REVIEW

**Comment by wperron** [comment]
I'm not sure this is necessary, creating a RegExp from a string is hardly a complicated step to do before using `assertMatch`

**Comment by lucacasonato** [comment]
@getspooky How is this different from `assertIncludesString`?

**Comment by getspooky** [comment]
@lucacasonato `assertMatch` uses include in order to match `string`, The purpose of this PR is to give more option.

**Comment by wperron** [comment]
Respectfully closing; constructing a `RegExp` from a string is already trivial.

**Pull request closed without merging**
