### PR TITLE
chore(CI): upgrade to ubuntu-22.04-xl

### PR DESCRIPTION
**Pull request by iuioiua**

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
cc @ry This probably will affects the CI costs

**Comment by lino-levan** [comment]
Given the removal of `std/node`, I wonder if the `xl` runners are unnecessary now.

**Comment by kt3k** [comment]
Closing in favor of #3235

More context: larger runners (`-xl`) were in preview, and were free to use (to my understanding). The preview will finish soon and the billing starts for it. (`ubuntu-20.04-xl` was for the preview usage and `ubuntu-22.04-xl` is not)

**Pull request closed without merging**
