### PR TITLE
refactor: replace use of `Deno.spawnChild` and `Deno.run` with `Deno.Command`

### LINKED ISSUE #2885: suggestion: use `Deno.Command` API
It just came out with Deno 1.28. Is it stable enough for use within the standard library?

If so, I'm happy to do it.

### PR DESCRIPTION
**Pull request by iuioiua**
Closes #2885.

### CODE REVIEW

**Comment by kt3k** [comment]
Looks like non-node unite tests (`deno task test`) are timed out?

**Comment by iuioiua** [comment]
Frankly, I don't know why the ws test in `examples/chat/server_test.ts` is failing. `server.kill()` should close any leaking ops. Any thoughts?

**Comment by kt3k** [comment]
> server.kill() should close any leaking ops. Any thoughts?

I think `kill` just sends a signal to the process, and it takes a little for the process to actually finish. `await command.status` seems like a way to prevent the resource/ops leakage

**Comment by kt3k** [comment]
80345e40d6bb46ca0eb630699065d2f24667f3ab was necessary for passing test with `--coverage` option. Otherwise it hanged at `[examples/chat] GET /ws should upgrade conn to ws` case.

**Comment by iuioiua** [comment]
Thanks! Good to know `command.status` is required. Documentation doesn't really explain the new `Deno.Command` API well. Anyway...

**Review by cjihrig — APPROVED** [review]

**Comment by bartlomieju** [comment]
Please wait before merging this PR for https://github.com/denoland/deno/pull/16812 to land - that way we can avoid double work

**Comment by cjihrig** [comment]
@bartlomieju would this be ok to land now that https://github.com/denoland/deno/pull/16812 has landed?

**Comment by bartlomieju** [comment]
@cjihrig yep!

**Comment by cjihrig** [comment]
@iuioiua there is a conflict now.

**Review by kt3k — APPROVED** [review]
LGTM. Nice work!

**Pull request merged**
