### PR TITLE
fix(streams): readableStreamFromReader returns byte stream (#1739)

### PR DESCRIPTION
**Pull request by matthewleon**
@crowlKats would you mind checking this for me?

### CODE REVIEW

**Comment by matthewleon** [comment]
Actually, let me close/pause this for now. It seems the code may need more extensive change to properly/efficiently handle BYOB requests.

**Comment by crowlKats** [comment]
@matthewleon do you want to give it another try, or want me to fix this?

**Comment by matthewleon** [comment]
@crowlKats I'll give it another try if you don't mind. The WhatWG standard has a reference implementation of this that I'll copy from tomorrow. Will try to write appropriate testing as well.

**Comment by crowlKats** [comment]
@matthewleon are you still going to try to do this?

**Comment by matthewleon** [comment]
No, sorry. Have moved on to other projects.

**Pull request closed without merging**
