### PR TITLE
fix(log): don't discard bytes >4096 in `FileHandler`

### PR DESCRIPTION
**Pull request by syhol**
Fixes the bug https://github.com/denoland/deno_std/issues/4411
Bug introduced in https://github.com/denoland/deno_std/pull/4021

TLDR; Attempting to log 4096 or more bytes in a single call to the logger would throw an error and the log would not be written.

Note this PR appears to introduce a new dependency between std/log and std/io. If this is not acceptable then we can find a workaround but the solution will be more verbose.

### CODE REVIEW

**Comment by syhol** [comment]
I'm not sure why canary is failing, I don't think it's related to my change as its failing in ./testing/snapshot_test.ts and I don't see any link between that and the log module.

**Review by iuioiua — CHANGES_REQUESTED** [review]

**Comment by kt3k** [comment]
> Note this PR appears to introduce a new dependency between std/log and std/io. If this is not acceptable then we can find a workaround but the solution will be more verbose.

We recently slightly changed the policy about `std/io` (ref: #4128), and now it's not a deprecated module anymore. So the dependency to `std/io` is just fine.

**Comment by syhol** [comment]
Looks like https://github.com/denoland/deno_std/pull/4416 fixed the canary issues, thanks for that @kt3k 🙏 

@iuioiua's suggestions have been merged and it's ready for another review.

**Review by kt3k — APPROVED** [review]
LGTM. Thanks!

**Review by iuioiua — APPROVED** [review]

**Comment by iuioiua** [comment]
Thank you, @syhol!

**Pull request merged**
