### PR TITLE
Add reusable prettier wrapper CLI

### LINKED ISSUE #159: Make prettier usable from other repositories.
```console
deno --allow-run --allow-write https://deno.land/x/prettier/main.ts
```

The command like the above should format the source code in any repository.

### PR DESCRIPTION
**Pull request by kt3k**
Created reusable formatter at `//prettier/main.ts`. You can use it like:

```console
deno --allow-run --allow-write https://deno.land/x/std/prettier/main.ts
```

See `//prettier/README.md` for more details.

---
close #159

### CODE REVIEW

**Comment by kt3k** [comment]
CI is red because `deno.exe` is not available in PATH on windows. (task.prependpath doesn't seem working only on windows...

**Comment by ry** [comment]
Hmmmm
@MarkTiedemann any ideas about this windows CI issue?

**Comment by kt3k** [comment]
I'm not sure this is ideal, but I changed the some steps in windows job from `script` to `bash`, and now CI passes.

([The document](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting?view=azdevops&tabs=yaml) says `script` step uses `cmd.exe` on windows, and `bash` step uses `Git Bash` on windows.)

**Comment by MarkTiedemann** [comment]
> Hmmmm I wonder what changed - it was working...
> @MarkTiedemann any ideas about this windows CI issue?

No idea. I might be able to investigate more deeply tomorrow when I have access to my Windows machine again.

I don't think any changes to deno_install caused this issue.

**Pull request merged**
