### PR TITLE
feat(encoding): added XML parser

### PR DESCRIPTION
**Pull request by JuanM04**
To-do:
- [x] Implement parser
  - [x] Add multiple outputs
  - [ ] Add tests
- [ ] Implement stringify
  - [ ] Add tests
  - [ ] Support multiple inputs (?)
- [x] Added `escape` utility

### CODE REVIEW

**Comment by kitsonk** [comment]
This is a lot of work. Has there been a conversation with a core team member about this being a good contribution to `deno_std`?  If so, it would be great to link to it or an issue where conversation has gone on.

**Comment by JuanM04** [comment]
I did not have any conversation about this. I was experimenting with XML and, since Deno has support for YAML, TOML, CSV, and other common formats, I thought this would be a nice addition. If you don't think this should be integrated in `deno_std`, I could easily extract it into its own package

**Comment by kt3k** [comment]
Is it possible to make this compatible with [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) API?

**Comment by andreubotella** [comment]
Note that @b-fuze is independently thinking of adding integration with the XML parser `xml5_ever` in their [deno_dom](github.com/b-fuze/deno-dom) library.

**Comment by kitsonk** [comment]
Having XML parser as part of [deno_dom](https://deno.land/x/deno_dom@v0.1.33-alpha) would be a lot better in my opinion. YAML, TOML, CSV are far more simplistic of parsers than XML.

**Comment by cjihrig** [comment]
This has been idle for a few months. @kitsonk @kt3k do we want to move forward with this? If not, can we close it out?

**Comment by kt3k** [comment]
I'm in favor of closing this one for now.

I agree with @kitsonk . I think we should have xml parser as part of DOM API instead of invented API.

**Pull request closed without merging**
