### PR TITLE
feat: add hmac implementation

### PR DESCRIPTION
**Pull request by luk3skyw4lker**
Adding HMAC implementation according to [crypto-browserify](https://github.com/crypto-browserify/createHmac/blob/master/browser.js)

Addressing #2557

### CODE REVIEW

**Comment by cjihrig** [comment]
Thanks for the PR. It looks like the CI is not happy with the current changes. Also, I think we would want to vendor the appropriate tests from the Node test suite for this.

**Comment by cjihrig** [comment]
Ping @luk3skyw4lker. Are you planning to revisit this?

**Comment by luk3skyw4lker** [comment]
@cjihrig Yes I am! I'm just a little caght up in some work stuff, I'll try to make some progress this weekend

**Comment by luk3skyw4lker** [comment]
@cjihrig about the tests, I'll take a look at the node tests suite and add the tests there

**Comment by luk3skyw4lker** [comment]
@cjihrig @kt3k @bartlomieju I am a little confused on how we should test this implementation, should I just create a test that validates the creation of the HMAC and check the consistency of the output (since it's a hash, same input should produce the same output) or something else? I can't think of a lot of options

**Comment by cjihrig** [comment]
@luk3skyw4lker were you able to identify tests in Node's suite for this functionality? If so, you can update [this file](https://github.com/denoland/deno_std/blob/main/node/_tools/config.json) with those tests, and then run `deno run --allow-read --allow-net --allow-write node/_tools/setup.ts` to refresh the test suite.

**Comment by luk3skyw4lker** [comment]
@cjihrig I didn't found the test suite in the deno_std repository, but I did found a test for it in the Node repository, so I should just copy the test file and update this file that you mentioned and everything should be done (assuming that the tests are approved)?

**Comment by cjihrig** [comment]
You don't need to copy the test files. If you update the linked config file and regenerate the test suite, it will pull in the tests that you add.

**Comment by luk3skyw4lker** [comment]
@cjihrig Alright! Thanks for the help!

**Comment by luk3skyw4lker** [comment]
@cjihrig FYI: I am currently working into fixing the broken node tests, I have found some inconsistencies in the code :x

**Comment by luk3skyw4lker** [comment]
@cjihrig you guys can take it over if needed, I'm pretty short on time to solve this, I wish I could do more, but it isn't possible for me :/

**Review by cjihrig — APPROVED** [review]
Nice work

**Pull request merged**
