### PR TITLE
feat(encoding/csv): merge files

### PR DESCRIPTION
**Pull request by timreichen**
- merges `csv.ts` and `csv_stringify.ts` as well as `csv_test.ts` and `csv_stringify_test.ts`
- add steps to tests

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM. Thanks!

**Comment by kt3k** [comment]
Should we keep `csv_stringify.ts` with alias exports for a while to prevent the breakage in user's code or just remove it (assuming it wasn't a public API 🤔  )? cc @bartlomieju

**Comment by bartlomieju** [comment]
> Should we keep `csv_stringify.ts` with alias exports for a while to prevent the breakage in user's code or just remove it (assuming it wasn't a public API 🤔 )? cc @bartlomieju

If it's not a big deal, maybe we could keep it around for 2-3 releases?

**Comment by timreichen** [comment]
I added `csv_stringify.ts` with redirections and deprecation notes.

**Comment by kt3k** [comment]
> I added csv_stringify.ts with redirections and deprecation notes.

Nice! Thanks!

**Pull request merged**
