### PR TITLE
chore: trim CODEOWNERS

### PR DESCRIPTION
**Pull request by iuioiua**
See https://github.com/denoland/deno_std/pull/3734#discussion_r1390172621

### CODE REVIEW

**Comment by kt3k** [comment]
In my view this file is useful. If the concern here is the maintenance cost of this file, maybe let's leave the only below line:

```
/*            @kt3k
```

**Comment by iuioiua** [comment]
What do we lose by removing this file? And WDYT, @bartlomieju?

**Comment by kt3k** [comment]
If the user name is listed in this file, that account will get 'participating' notification, which is useful in my case.

**Comment by crowlKats** [comment]
Due to the streams folder, this is useful for me, and especially once #3119 lands, having this will be even more useful for me. We can just simplify the file to:
```
* @kt3k
/streams @kt3k @crowlKats 
```
Then there should be no concerns in terms of maintainability.

**Comment by iuioiua** [comment]
Fair points. I've adjusted it to be the Leo's snippet.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
