### PR TITLE
Expose fileServer options and move file_server start to examples

### PR DESCRIPTION
**Pull request by hayd**
xlink: #79

### CODE REVIEW

**Comment by hayd** [comment]
On linux this is getting this error:

```
HttpOther: an error occurred trying to connect: Connection refused (os error 111)
```
which is strange, as this ought to be doing the same thing as before...

**Comment by bartlomieju** [comment]
I wonder if this is related to: denoland/deno#1195, could you try passing different port, eg. `4001`?

**Comment by hayd** [comment]
@ry `http/file_server_test.ts` tests against `examples/file_server.ts`.

I'll rebase and see if it's still showing the same Connection refused error on linux...

**Comment by hayd** [comment]
Same error 🤔

**Comment by bartlomieju** [comment]
@hayd this PR is pretty stale... I think `file_server` is fine in `http/`

**Comment by ry** [comment]
Agree

**Pull request closed without merging**
