### PR TITLE
[Server] Improve type info. Remove dead code

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by sh7dm** [comment]
@MaxGraey looks like you need to run `deno -A format.ts`

**Comment by ry** [comment]
With 0.2.10 it should be sufficient to do deno —fmt .

**Comment by sh7dm** [comment]
@ry yes, I forgot about it

**Comment by MaxGraey** [comment]
I tried `deno —fmt .`, `deno -A tools/format.ts`, also set abs path, but always got this message:
```
Cannot resolve module "—-fmt" from "."
```
Also very strange behaviour:
deno-fmt

**Pull request closed without merging**
