### PR TITLE
node: Use "Deno.spawnChild" API for "child_process" polyfill

### PR DESCRIPTION
**Pull request by bartlomieju**
Prerequisite for https://github.com/denoland/deno_std/pull/2395

### CODE REVIEW

**Review by cjihrig — APPROVED** [review]
LGTM but the CI is failing.

**Comment by kt3k** [comment]
It looks like that `end` events on `child.stdout` and `child.stderr` are not firing after the child is killed according to the test failure. I'll look into more details.

**Comment by kt3k** [comment]
Removing `this.stdout.destroy()` and `this.stderr.destroy()` calls in `kill()` function seemed solving the issue.

**Comment by bartlomieju** [comment]
Thanks for looking into it Yoshiya!

**Pull request merged**
