### PR TITLE
chore(bytes): release `bytes@1.0.0-rc.2`

### PR DESCRIPTION
**Pull request by iuioiua**
Mainly for the docs changes.

### CODE REVIEW

**Comment by iuioiua** [comment]
Maybe we should add a new PR title type `release` just for releases.

**Comment by kt3k** [comment]
In my opinion version bump should be tagged with `chore:`. This doesn't add any new feature

**Comment by kt3k** [comment]
BTW this version upgrade will automatically happen by https://jsr.io/@deno/bump-workspaces in the next release flow. Any change in prerelease version package causes the increment of the last fragment of prerelease id.

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by iuioiua** [comment]
True - this doesn't add any feature. Changed it to chore and will do for releases from now on.

**Pull request merged**
