### PR TITLE
#2245 assertSnapshot errors on empty snapshot in non-update mode

### PR DESCRIPTION
**Pull request by cuobiezi**

### CODE REVIEW

**Comment by bartlomieju** [comment]
@cuobiezi thanks for the PR, please rebase against `main` branch

**Comment by kt3k** [comment]
@cuobiezi The invalid permission name handling was updated in Deno CLI recently in https://github.com/denoland/deno/pull/14676. You need to upgrade Deno to the latest version

**Comment by kt3k** [comment]
The change looks good to me. The snapshot assertion looks still failing on some cases. Can you update them?

**Comment by cuobiezi** [comment]
> @cuobiezi The invalid permission name handling was updated in Deno CLI recently in https://github.com/denoland/deno/pull/14676. You need to upgrade Deno to the latest version

Seem didn't release yet .let me try to install by source .Thanks

**Comment by cuobiezi** [comment]
> The change looks good to me. The snapshot assertion looks still failing on some cases. Can you update them?

Yup Let me try

**Comment by cuobiezi** [comment]
@kt3k @bartlomieju  Done, Thanks.

**Review by bartlomieju — APPROVED** [review]
Looks good! Thanks @cuobiezi

**Pull request merged**
