### PR TITLE
chore(fs): remove flaky `emptyDir()` tests

### PR DESCRIPTION
**Pull request by iuioiua**
This PR removes flaky `emptyDir()` and `emptyDirSync()` [tests](https://github.com/denoland/deno_std/actions/runs/7283505986/job/19847485371).

These tests test Deno's permissions system, which is a runtime concern and outside the scope of the Standard Library. These tests were written a while ago in https://github.com/denoland/deno/pull/3501 and the permission system is a lot more robust today. I think it's fine for these tests to be removed.

Note: test coverage is not affected.

### CODE REVIEW

**Comment by kt3k** [comment]
What is the source of flakiness?

**Comment by iuioiua** [comment]
Most likely, the heavy use of `Deno.Command()` in parallel.

**Comment by kt3k** [comment]
> These tests test Deno's permissions system, which is a runtime concern and outside the scope of the Standard Library.

I disagree with this. This tests `emptyDir` requiring expected permissions. I don't think it's a good idea to remove these.

**Comment by iuioiua** [comment]
I'll close this for now until we confirm the cause of the flakes.

**Comment by iuioiua** [comment]
Related #4022

**Pull request closed without merging**
