### PR TITLE
ci: bump to v0.13.0

### PR DESCRIPTION
**Pull request by ry**
merge on approval

### CODE REVIEW

**Comment by ry** [comment]
Windows is failing with
```
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/db24355d-291c-4c00-b0b8-c1fe00084c1f.sh
Compile file:///D:/a/1/s/format.ts
Compile file:///D:/a/1/s/prettier/main.ts
a\1\s\colors\mod.ts.js ... Not formatted
a\1\s\format.ts.js ... Not formatted
a\1\s\fs\path\interface.ts.js ... Not formatted
a\1\s\fs\glob.ts.js ... Not formatted
a\1\s\fs\path\mod.ts.js ... Not formatted
a\1\s\prettier\prettier.ts.js ... Not formatted
a\1\s\prettier\util.ts.js ... Not formatted
a\1\s\flags\mod.ts.js ... Not formatted
a\1\s\fs\path\constants.ts.js ... Not formatted
a\1\s\fs\walk.ts.js ... Not formatted
a\1\s\fs\globrex.ts.js ... Not formatted
a\1\s\fs\path\utils.ts.js ... Not formatted
a\1\s\fs\path\posix.ts.js ... Not formatted
a\1\s\testing\pretty.ts.js ... Not formatted
a\1\s\fs\path\win32.ts.js ... Not formatted
a\1\s\prettier\main.ts.js ... Not formatted
a\1\s\testing\asserts.ts.js ... Not formatted
a\1\s\testing\diff.ts.js ... Not formatted
a\1\s\testing\format.ts.js ... Not formatted
Some files are not formatted
```

not sure why (cc @kt3k)

**Comment by kt3k** [comment]
@ry 

> a\1\s\colors\mod.ts.js ... Not formatted
> a\1\s\format.ts.js ... Not formatted
> a\1\s\fs\path\interface.ts.js ... Not formatted

Filenames look strange to me. Are those files transpiled from typescript? They look something which shouldn't exist there..

**Comment by bartlomieju** [comment]
> Filenames look strange to me. Are those files transpiled from typescript? They look something which shouldn't exist there..

They are, however they should only be placed in `DENO_DIR`, not in the same directory as project code. I'm debugging

**Comment by bartlomieju** [comment]
The problem seems to be with `$DENO_DIR` since it's not defined it's falling back to each system specific cache directory. Somehow on Windows it ends up being `a` directory in current directory:
```
drwxr-xr-x 1 VssAdministrator 197121    0 Aug 10 10:26 a
drwxr-xr-x 1 VssAdministrator 197121    0 Aug 10 10:24 archive
-rw-r--r-- 1 VssAdministrator 197121  477 Aug 10 10:24 azure-pipelines.yml
```

I'm working on updating CI scripts to set `$DENO_DIR` to location outside of project directory in pipeline

**Comment by bartlomieju** [comment]
I've got the problem...
https://github.com/denoland/deno/blob/286ee1d8b68b54d39e698f3b78e3ce9e257fa674/cli/disk_cache.rs#L21-L24

I'm gonna start fixing it now, @ry would you be able to cut v0.14.1 release so we can release standard lib?

**Comment by ry** [comment]
handed in #556

**Pull request closed without merging**
