### PR TITLE
CI should fail if format.ts changes files

### LINKED ISSUE #77: CI should fail if format.ts detects differences
We do this in core with https://github.com/denoland/deno/blob/master/tools/test_format.py

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #77 

I wrote it in Deno 🎉

### CODE REVIEW

**Comment by bartlomieju** [comment]
Azure piplines report green, even though command throws `PermissionDenied`, @ry any idea why that happens?

**Comment by ry** [comment]
@bartlomieju Let's not do the submodule thing here just for prettier. The ideal solution would be if we could bundle prettier and run it from Deno instead of Node....

(Actually the ideal solution would be to have a new minimal formatted that used the TS compiler... but that's difficult.)

**Comment by bartlomieju** [comment]
https://www.npmjs.com/package/typescript-formatter

**Comment by ry** [comment]
Closing old PRs. I'd love to have this working, but it needs to be green. Please open a new PR if you can. Otherwise I'll swing back to this patch for reference when I have time to do this.

**Pull request closed without merging**
