### PR TITLE
chore(ci): add informational Codecov status checks

### PR DESCRIPTION
**Pull request by thomasrockhu-codecov**
Hi, Tom from Codecov here. I noticed that you were using Codecov but weren't actually getting any notifications on pull requests. I figured it would be useful to get some idea if code being changed is being tested, but also not blocking CI/merging. Let me know if this makes sense or if we can do something that would be helpful.

### CODE REVIEW

**Comment by kt3k** [comment]
@thomasrockhu-codecov Thanks for the PR.

> but also not blocking CI/merging.

Does this mean the status from codecov is always green with this settings?

**Comment by kt3k** [comment]
@thomasrockhu-codecov Thanks for the clarification. Can you also sign the CLA from the above link?

I think this is worth trying.

@bartlomieju What do you think?

**Comment by lucacasonato** [comment]
Seems fine.

**Comment by bartlomieju** [comment]
Seems good to me. @thomasrockhu-codecov can you sign the CLA so we can land the PR?

**Review by littledivy — APPROVED** [review]

**Review by kt3k — APPROVED** [review]

**Pull request merged**
