### PR TITLE
Allow: err instanceof Deno.errors.AlreadyExists

### PR DESCRIPTION
**Pull request by RefinedSoftwareLLC**
// replaced `new Error` with `new Deno.errors.AlreadyExists` when appropriate. Enables:
```
try {
  copySync('src',  'dest', { overwrite: false })
  copySync('src',  'dest', { overwrite: false }) // already exists
} catch(err) {
  if (err instanceof Deno.errors.AlreadyExists == false) { throw err } // only ignore AlreadyExists error
}
```

### CODE REVIEW

**Comment by RefinedSoftwareLLC** [comment]
This already works:
```
try {
  Deno.mkdirSync('./temp')
  Deno.mkdirSync('./temp') // already exists
} catch(e) {
  if (e instanceof Deno.errors.AlreadyExists == false) { Deno.exit(2) }
}
```

**Comment by RefinedSoftwareLLC** [comment]
ci/lint should not have failed, it is recommending to make the code worse and not match the rest of each file.

**Review by kt3k — COMMENTED** [review]
Thanks for your contribution.

The changes in `fs/` and `testing/` make sense to me. I think the changes in `node/` don't make much sense because these are node compatible layer. We shouldn't throw deno specific error from the code in `node/`

**Comment by RefinedSoftwareLLC** [comment]
[node/_fs/_fs_open.ts](https://github.com/denoland/deno_std/blob/9c269464b111517e305df9a61f5b6e6b55cf6701/node/_fs/_fs_open.ts) already expects and throws Deno Errors like in ```throw new Deno.errors.AlreadyExists(`A file exists at the destination: ${destStr}`);```

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
