### PR TITLE
feat: add assertNotThrows/assertNotThrowsAsync for testing/assert module

### PR DESCRIPTION
**Pull request by axetroy**

### CODE REVIEW

**Comment by zekth** [comment]
A bit overkill no? Because if the assert throws, the test gets an exception and make it fail.

**Comment by axetroy** [comment]
@zekth

Because I have write the test case with `assertThrows/assertThrowsAsync`.

In some scenarios, in order to implement `assertNotThrowsAsync`

I have to write like this:

https://github.com/denoland/deno_std/blob/fae48d5dfbbe6267c71a0dc48647548b190dd875/fs/write_json_test.ts#L35-L46

I can do this more simply and clear with `assertNotThrowsAsync`.

```typescript
await Deno.writeFile(existsJsonFile, new Uint8Array());

await assertNotThrowsAsync(() => writeJson(existsJsonFile, { a: '1' }));

const content = await Deno.readFile(existsJsonFile);
```

**Comment by zekth** [comment]
> Some cleaning work cannot be done

May hooks have to be added to the `test()` function.

**Comment by axetroy** [comment]
Yes, I think about it again. It really is not suitable

**Pull request closed without merging**
