### PR TITLE
refactor(archive): format test names

### PR DESCRIPTION
**Pull request by timreichen**
Ref: https://github.com/denoland/deno_std/issues/3754

### CODE REVIEW

**Review by iuioiua — APPROVED** [review]
LGTM. Thank you.

**Comment by iuioiua** [comment]
Note to self: use these names in #1985.

**Comment by kt3k** [comment]
I wonder if the expression like `Tar()` makes sense as `Tar` is a class here

**Comment by iuioiua** [comment]
What do you suggest?

**Comment by kt3k** [comment]
If a test case is simple enough, I think we can use something like:

```js
Deno.test("Tar", (t) => {
  t.step("append() blah blah", () => {});
  t.step("getReader() blah blah", () => {});
});
```

**Comment by kt3k** [comment]
But if a test case is complex and needs to involve multiple APIs (in other words, integration test type ones), maybe we need to allow more arbitrary format

**Pull request merged**
