### PR TITLE
chore(node/_tools): Set up with Node v15.5.1

### PR DESCRIPTION
**Pull request by wafuwafu13**
After: https://github.com/denoland/deno_std/pull/1375

`NotFound` Error occurred during setup.

```zsh
 ~/desktop/deno_std
 $ deno run --allow-read --allow-net --allow-write node/_tools/setup.ts
 File "versions/node-v15.5.1.tar.gz" found, use file? Y/N: y
 Decompressed file "versions/node-v15.5.1" found, use file? Y/N: y
 Cleaning up previous tests
 Copying test files...
 error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
     const srcFile = await Deno.open(
                     ^
     at deno:core/01_core.js:101:46
     at unwrapOpResult (deno:core/01_core.js:121:13)
     at async Object.open (deno:runtime/js/40_files.js:51:17)
     at async copyTests (file:///Users/tagawahirotaka/Desktop/deno_std/node/_tools/setup.ts:210:21)
     at async file:///Users/tagawahirotaka/Desktop/deno_std/node/_tools/setup.ts:289:1
```

When I run the following script(`node/_tools/checkExist.ts`) locally, I find that a file that does not exist in node v15.5.1 is specified in `config.json`.

```ts
 import { config } from "./common.ts";
 
 let node15Tests = []
 for await (const entry of Deno.readDir('node/_tools/versions/node-v15.5.1/test/parallel')) {
   node15Tests.push(entry.name);
 }
 
 for (const test of config.tests.parallel) {
   if (!node15Tests.includes(test)){
     console.log(test)
   }
 }
...
```

```zsh
 $ deno run --allow-read node/_tools/checkExist.ts
 Check file:///Users/tagawahirotaka/Desktop/deno_std/node/_tools/checkExist.ts
 test-net-server-listen-options-signal.js
 test-dns-idna.js
 test-net-connect-econnrefused.js
```

I deleted these files from `config.json` and ran the setup again.

I suspect @cmorten didn't set up with v15.5.1 or https://github.com/denoland/deno_std/issues/1317 (My Solution) is related 🤔

### CODE REVIEW

**Comment by cmorten** [comment]
@wafuwafu13 as you suspect, with the outstanding tooling issues I didn’t use the setup tool for the net module work, hoping instead someone would resolve that and then could come back and fix any mistakes in my manual copying.

**Comment by cmorten** [comment]
> Would it be better to comment out the following unpassed tests?
> 
> https://github.com/denoland/deno_std/pull/1385/checks?check_run_id=3869639162#step:4:58916
> 
> ```shell
> failures:
> 
> 	suites/parallel/test-net-connect-immediate-finish.js
> 	suites/parallel/test-net-reconnect.js
> 	suites/parallel/test-net-write-arguments.js
> 	suites/parallel/test-net-better-error-messages-port-hostname.js
> 	suites/internet/test-dns-ipv4.js
> 	suites/internet/test-dns-ipv6.js
> 	suites/internet/test-dns.js
> 	suites/internet/test-dns-lookup.js
> ```

Hmm, something must have regressed as they passed in ci for #1375.

**Comment by kt3k** [comment]
@wafuwafu13 

> I think we can fix this by upgrading Node version (I'll wait to others opinion).

I'm in favor of upgrading Node.js version. Node.js community doesn't maintain 15.x versions anymore (ref: https://nodejs.org/en/about/releases/ ). So it doesn't make much sense to keep this version here IMO.

**Comment by wafuwafu13** [comment]
We have not upgraded since the initial setup :eyes:
https://github.com/denoland/deno_std/pull/695/files#diff-1e332023c25d6347d610343825902ed180e0f55524d7b26e7d44d010b0653c48R2

If there are no more comments here, I'll close this PR and upgrade to v16.11.1 in new PR.
https://nodejs.org/en/download/releases/

**Pull request closed without merging**
