### PR TITLE
fix(encoding): add validation of the input types

### PR DESCRIPTION
**Pull request by kt3k**
This PR adds the validation of the input type for encoding APIs.

### CODE REVIEW

**Review by lino-levan — COMMENTED** [review]
This PR in it's current state LGTM. It solves the problem in the title. I just question whether it makes sense to add runtime validation for these things. Typescript should prevent people from putting in an invalid input? I don't know if this is worth the additional runtime cost.

**Comment by kt3k** [comment]
A user can opt-out from typescript in Deno. In that case, they don't see type error for wrong input types.

Also a user can specify wrong types by mistake:
```js
const result: { data: string }  = await response.json();
encodeBase64(result.data); // `result.data` can be a number if the response is not intended one
```

In those cases, throwing validation error will be useful, I think.

**Comment by lino-levan** [comment]
Makes sense to me. Just making sure this was the reasoning.

**Review by bartlomieju — APPROVED** [review]
LGTM 👍

**Pull request merged**
