### PR TITLE
[WIP] feat: add http client module

### PR DESCRIPTION
**Pull request by axetroy**
ref #284

If you think that this should be what `std package` should do, then I will continue to complete the rest.

or it should be done by a `third-party library`?

how do you think

### CODE REVIEW

**Comment by ry** [comment]
There's already `fetch()` in the global scope. What would this add?

**Comment by axetroy** [comment]
@ry Fetch-based encapsulation provides a faster way to send an HTTP request.

Maybe people think that the interface of the `axios` class is better than `fetch`.

So try to integrate into std

**Comment by hayd** [comment]
Is this like python's requests library?

I wonder if this should be in requests directory (and take ideas from that API)? There's also a Scala port requests and it's really great.

**Comment by kitsonk** [comment]
I think if there is a decent standard that is part of the web platform (`fetch()`) that we shouldn't cloud `std` with overlapping APIs.  While some people might not like the API, that alone is not a good reason to confuse people.  It is better off left just in the registry.

**Comment by axetroy** [comment]
I think so too.

just asking for your opinions.

End the discussion.

**Pull request closed without merging**
