### PR TITLE
datetime: correct hh:mm formats and add test cases

### PR DESCRIPTION
**Pull request by 43081j**
Adding a few tests.

Guess nobody uses this module much either seeing as half the formats had incorrect regex, so I fixed that too.

### CODE REVIEW

**Comment by kevinkassimo** [comment]
@43081j Yikes. Yeah it is added just last week... Thanks
@sh7dm Please review

**Comment by 43081j** [comment]
also we could do with an `assert.fail` or a way to assert for exceptions being thrown as I currently have to try/catch it and force an assertion failure.

**Comment by ry** [comment]
> also we could do with an assert.fail or a way to assert for exceptions being thrown as I currently have to try/catch it and force an assertion failure.

Sounds useful. I think it would be best placed in the “testing” module

**Comment by kitsonk** [comment]
Side note, I was trusted with the same and worked on a PR last night. Will raise it in a few mins.

**Comment by kitsonk** [comment]
I raised this as #124 as I already had it mostly done.

**Comment by ry** [comment]
Please rebase

**Comment by 43081j** [comment]
@ry :shipit:

**Pull request merged**
