### PR TITLE
feat(yaml): make APIs public

### PR DESCRIPTION
**Pull request by iuioiua**
Looking at [js-yaml](https://github.com/nodeca/js-yaml), it appears as though `load()`, `dump()`, and related functions/interfaces should be public. This change does that.

It's possible that interfaces within `loader/loader_state.ts` and `dumper/dumper_state.ts` should not be included in the public API. A second opinion would be appreciated.

Related:
* #3256

### CODE REVIEW

**Comment by kt3k** [comment]
`load` and `dump` are very similar (almost identical) to `parse` and `stringify`. It doesn't make much sense to export them in addition to the existing APIs in my view.

**Comment by lino-levan** [comment]
We should investigate why https://github.com/ubersl0th/markdown/pull/17 needed to use `load` over `parse`. Maybe there is a use case?

**Comment by iuioiua** [comment]
> `load` and `dump` are very similar (almost identical) to `parse` and `stringify`. It doesn't make much sense to export them in addition to the existing APIs in my view.

Oh, yeah, they're identical. That was something I should've obviously checked.

> We should investigate why [ubersl0th/markdown#17](https://github.com/ubersl0th/markdown/pull/17) needed to use `load` over `parse`. Maybe there is a use case?

Check out https://github.com/denoland/deno_std/blob/main/yaml/parse.ts

**Comment by lino-levan** [comment]
They are quite literally identical, nevermind.

**Pull request closed without merging**
