### PR TITLE
chore: add `ok` task

### PR DESCRIPTION
**Pull request by iuioiua**
This change adds the `ok` task, which is a holistic task checking that formatting, linting and tests all look good.

### CODE REVIEW

**Comment by kt3k** [comment]
I prefer to keep `lint` CI job. By this change `lint` job runs on all platforms and with 2 deno versions. That looks unnecessary and waste of CI time

**Comment by iuioiua** [comment]
Yes, the `lint` job would run on all platforms and with 2 versions of the Deno runtime. However, I think this is a worthwhile tradeoff. Do consider:
- We gain simpler CI.
- We use normal-sized runners, which are free.
- The difference in CI times is arguably imperceptible compared to the current CI setup (see [here](https://github.com/denoland/deno_std/actions/workflows/ci.yml)).

**Comment by kt3k** [comment]
`deno fmt` sometimes has breaking changes. In that case, this CI setup doesn't pass.

Another downside is that `lint` failure is now not visible in PR page.

> We gain simpler CI.

I would choose faster CI setup rather than simpler CI setup

**Comment by iuioiua** [comment]
Fair enough. I'll revert the CI changes. We'd still have the benefit of contributors being able to use `deno task ok` for local development.

**Review by kt3k — APPROVED** [review]
LGTM.

BTW `deno task lint` doesn't include `deno fmt --check`. Maybe you'd like to include it to `deno task ok` as well?

**Review by kt3k — APPROVED** [review]
LGTM again!

**Pull request merged**
