### PR TITLE
deprecate(log): deprecate internal utility methods

### PR DESCRIPTION
**Pull request by timreichen**
Ref: https://github.com/denoland/deno_std/issues/4392#issuecomment-1975379295

**Changes**
- Deprecates `BaseHandler.log()` and introduces private `BaseHandler.#log()`
- Deprecates `ConsoleHandler.applyColors()` and introduces private `ConsoleHandler.#applyColors()`
- Deprecates `FileHandler.flush()` and introduces private `FileHandler.#flush()`
- Deprecates `Logger.asString()` and introduces private `Logger.#asString()`
- Deprecates `RotatingFileHandler.rotateLogFiles()` and introduces private `RotatingFileHandler.#rotateLogFiles()`

### CODE REVIEW

**Comment by iuioiua** [comment]
@kt3k, PTAL, including my reasons for supporting this change, linked to in the initial comment.

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by roj1512** [comment]
@timreichen See #4571.

**Comment by roj1512** [comment]
Related: #4436

**Pull request merged**
