### PR TITLE
fix(node): enable some `pseudo-tty` tests

### PR DESCRIPTION
**Pull request by iuioiua**
Sorry, re-create of #2587. Initially, this aimed to enable the `stdin-setrawmode.js` test, mentioned in #1579. However, it's still not passing, which I hoped/guessed it would've. Nevertheless, I've enabled other tests from `pseudo-tty` which are passing.

### CODE REVIEW

**Comment by kt3k** [comment]
I think we probably need to modify `getPathsFromTestSuites` (in `node/_tools/common.ts`) to actually include these test cases.

**Comment by iuioiua** [comment]
> I think we probably need to modify `getPathsFromTestSuites` (in `node/_tools/common.ts`) to actually include these test cases.

Done.

**Review by kt3k — APPROVED** [review]
LGTM. Thanks!

**Comment by kt3k** [comment]
Will land when the outage of windows-xl runner availability is resolved

**Pull request merged**
