### PR TITLE
chore: update windows VM version in CI

### PR DESCRIPTION
**Pull request by iuioiua**
`ubuntu-22.04-xl` will soon be deprecated (see [here](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/)).

### CODE REVIEW

**Comment by kt3k** [comment]
The change to `windows-2022-xl` looks fine, but `ubuntu-22.04-xl` doesn't seem running in the CI. It looks stuck with the message `Waiting for a runner to pick up this job...`

I guess the release/deprecation schedule for `-xl` runners are different from normal sized runners.

**Comment by iuioiua** [comment]
Are larger runners supposed to be created at the organisation level? Documentation [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners#adding-a-larger-runner-to-an-organization).

**Comment by kt3k** [comment]
> Are larger runners supposed to be created at the organisation level? Documentation [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners#adding-a-larger-runner-to-an-organization).

Thanks for the info. This looks interesting! I'll look into it.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
