### PR TITLE
std/io/bufio - Parameterize input TextEncoder in `readLines` and `readStringDelim`

### PR DESCRIPTION
**Pull request by carragom**
Here is an attempt to implement what is proposed on #920, please let me know what you think.

### CODE REVIEW

**Comment by kt3k** [comment]
@carragom Thank you for your contribution! I think this is a nice addtion to the API.

Can you run `deno fmt` command to the changed files?

**Comment by carragom** [comment]
Hi, thanks for the review, I formatted the files. But the reason the tests are failing is because the new test requires read access to be able to open the file with the encoded data. Not sure where to change that.

**Review by kt3k — APPROVED** [review]
@carragom Thanks! LGTM

**Comment by kt3k** [comment]
Note: mdn doesn't seem documenting `ignoreBOM` option? ref: https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder . But it's documented in whatwg spec https://encoding.spec.whatwg.org/#interface-textdecoder , and deno actually implements it.

**Pull request merged**
