### PR TITLE
fix(node): issues with browser

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by kt3k** [comment]
How did you get affected by this?

**Comment by roj1512** [comment]
I am `deno bundle`ing a project that is using `/node/fs.ts` and importing it from browser.

**Review by cjihrig — APPROVED** [review]

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
@roj1512 Do you know how `node/fs.ts` is depended in your dependency tree?

If the usage looks common/useful enough, maybe we can add some checks in CI to prevent this happening again.

**Pull request merged**
