### PR TITLE
feat: add envalid module

### PR DESCRIPTION
**Pull request by roj1512**
https://deno.land/x/envalid ([roj1512/envalid](https://github.com/roj1512/envalid)) is a port of the [npm.im/envalid](https://npm.im/envalid) ([af/envalid](https://github.com/af/envalid)) with slight modifications.

It makes using environment variables super easy and type-safe.

### CODE REVIEW

**Comment by roj1512** [comment]
Related: https://github.com/denoland/deno/issues/13396

**Comment by kt3k** [comment]
I feel this tool doesn't have enough common value/popularity to be included in deno_std.

I found this download graph, for example, about config management tools in npm
https://npmtrends.com/config-vs-convict-vs-dotenv-vs-envalid

dotenv is really popular, but envalid doesn't have comparable download counts.

**Comment by roj1512** [comment]
@kt3k I want other opinions before we vanish the PR.

**Comment by roj1512** [comment]
> I found this download graph, for example, about config management tools in npm
> [npmtrends.com/config-vs-convict-vs-dotenv-vs-envalid](https://npmtrends.com/config-vs-convict-vs-dotenv-vs-envalid)

1. We [need](https://github.com/denoland/deno/issues/13396) computed types.
2. If ever worked on, porting something like convict or config won't help be consistent, as they are not based on dotenv.

**Comment by imjamesb** [comment]
-1

I think that there are MANY ways to do data validation and there are a lot of preferences here. Data validation is such a big topic and in my own opinion I don't think Deno is ready to have a standard data validation module yet, not because the core team or the contributors wouldn't be able to make something out, but because Deno is opinionated, if Deno should have a data validation module in the standards it should be a lot of discussion around implementation and design on that module so it is efficient and feature rich, but still aligns well with Deno and it's design.

**Comment by GerbenRampaart** [comment]
I was not familiar with envalid but I am now, and I do like it a lot.

**Comment by timreichen** [comment]
I agree with @imjamesb. This is a very specific use case of object validation. I think std should have a data validation module that is flexible, extendable and applicable to many use cases as well as non-opinionated as possible.

**Comment by roj1512** [comment]
Also, this is not a data validator. It's envalid — environment validator.

**Comment by roj1512** [comment]
If in the future a data validation module was added to the std, we can make it use that.

**Comment by cjihrig** [comment]
I'm also -1 to including this in std. We can revisit the decision in the future, but I'm going to close this for now. Thank you for the PR though.

**Pull request closed without merging**
