### PR TITLE
refactor(csv): simplify `parseRecord()`

### PR DESCRIPTION
**Pull request by timreichen**
- removes nesting for more clarity

### CODE REVIEW

**Review by iuioiua — COMMENTED** [review]
Are you able to break this up into smaller PRs?

**Comment by timreichen** [comment]
> Are you able to break this up into smaller PRs?

https://github.com/denoland/deno_std/pull/5297

**Review by iuioiua — APPROVED** [review]
Nice. @kt3k, PTAL.

**Comment by kt3k** [comment]
I don't understand what's improved in this change.

**Comment by iuioiua** [comment]
Mostly, it reduces removes unnecessary logic for when `line.length === 0` and slightly reduces nesting.

**Comment by timreichen** [comment]
> I don't understand what's improved in this change. This introduces another label for indicating inner loop, and introduce several `continue label` statements. That doesn't feel 'simplification' to me

I actually think it is more readable and clearer to understand. I imagine that this can help extracting some logic into that can be shared between the two files in another PR.

**Comment by kt3k** [comment]
Nesting level seems exactly the same. Looks like just swapping the if-clause and else-clause randomly. Also increased number of lines seem concerning. I think we should avoid this kind of random change.

Closing without merge.

**Pull request closed without merging**
