### PR TITLE
feat: redis module

### PR DESCRIPTION
**Pull request by iuioiua**
This PR introduces the `redis` module to the Standard Library. It's a port of the [`r2d2` module](https://github.com/iuioiua/r2d2).

I understand there has yet to be a consensus on whether database connectors should exist within the Deno Standard Library. I am not 100% for it myself. Doing so may be outside the scope of this repo and may add too much managerial overhead. Nevertheless, having the implementation done would make the debate easier to settle, whether the consensus is for or against it.

Previously, #2238 attempted to port over [`deno-redis`](https://deno.land/x/redis) to the Standard Library. This implementation has some advantages that, I believe, may fit into this repo better:
1. It has no external dependencies outside of the Standard Library.
1. It has 100% test coverage but doesn't add time to CI workflows. It does this using a [Redis service container](https://docs.github.com/en/actions/using-containerized-services/about-service-containers). Note: A separate `redis` job had to be created for CI as the Redis service as it's only supported in Ubuntu runners.
1. Performant - The fastest Redis library in JavaScript (up to 35% faster than the next implementation, AFAIK).
1. It was written to be low-maintenance and easily understood. This is mostly thanks to it being functional instead of object-oriented. Also, it deliberately does not implement individual commands but offers a general-purpose but full-featured interface to Redis without unneeded intermediate abstractions.
1. Supports [RESPv2](https://github.com/iuioiua/r2d2#respv2), [RESP3](https://github.com/iuioiua/r2d2#resp3), [raw data](https://github.com/iuioiua/r2d2#raw-data), [pipelining](https://github.com/iuioiua/r2d2#pipelining), [pub/sub](https://github.com/iuioiua/r2d2#pubsub), [transactions](https://github.com/iuioiua/r2d2#transactions), [eval scripts](https://github.com/iuioiua/r2d2#eval-script) and [Lua scripts](https://github.com/iuioiua/r2d2#lua-script).
1. Compatible with [timeouts](https://github.com/iuioiua/r2d2#timeouts) and [retries](https://github.com/iuioiua/r2d2#retries).
1. It has been tested in production on my own site, [anhii.com](https://anhii.com/). I haven't had any real issues with it since adding it in. Actual implementation code can be seen [here](https://github.com/anhii/anhii/blob/main/routes/index.tsx#L8), [here](https://github.com/anhii/anhii/blob/main/routes/search.tsx#L25) and [here](https://github.com/anhii/anhii/blob/main/utils/redis.ts).

Todo:
- [ ] Expose the `redis` folder to Codecov.

Related:
- #2224

I'd love to hear what others think and any concerns.

### CODE REVIEW

**Comment by lino-levan** [comment]
Oh wow. This will surely spark some vivid discussion. I'll start off with my take: not quite sure how to feel about this.

In general, standard libraries (that I know of) don't really implement any database drivers (outside of *maybe* sqlite). I don't know if there is good reasoning for this (outside of managerial overhead). I'm sure this has been proposed elsewhere and we should verifying that the reasoning that it didn't work for other std libs doesn't apply to us.

**Comment by iuioiua** [comment]
Few things:
1. I realise I should delete `redis/README.md`.
2. The failing tests appear to be unrelated to this PR.
3. How could I ensure coverage is measured for Redis tests and the rest?

Before proceeding with further work on this PR, @kt3k, how do you and the team feel about this PR?

**Comment by kt3k** [comment]
Sorry for the delayed response

> I understand there has yet to be a consensus on whether database connectors should exist within the Deno Standard Library.

The current policy is that we don't include library/tools for software from specific vendors, and redis client falls into that category. We also didn't land sqlite client (#2230) for the same reason. So I don't think we can land this as is.

**Comment by iuioiua** [comment]
I understand, except for the "as is" part. Are you entertaining the implementation if it were tweaked? If not, all good. I'll close this PR.

**Comment by kt3k** [comment]
I was wondering if RESP can be considered as a vendor independent specification (in that case, RESP parse/serializer doesn't violate std's policy), but also RESP protocol doesn't seem adopted except redis. So I'd suggest we should close this for now.

**Pull request closed without merging**
