### PR TITLE
flip the order of the arguments of listen and dial.

### PR DESCRIPTION
**Pull request by diasbruno**
Hi,

this is the additional changed regarding issue [denoland/deno/issues/2056](https://github.com/denoland/deno/issues/2056).

Let me know if there is something to improve in this PR.

### CODE REVIEW

**Comment by hayd** [comment]
@ry this (and a release) is needed for 0.19.0 support in std/http.

**Comment by ry** [comment]
@hayd https://github.com/denoland/deno_std/pull/613

**Comment by nayeemrmn** [comment]
This should be closed.

**Comment by ry** [comment]
This was done - thanks

**Pull request closed without merging**
