### PR TITLE
Updated mod.ts as linter wants

### PR DESCRIPTION
**Pull request by handlederror**
I updated my pull request [https://github.com/denoland/deno_std/pull/820](https://github.com/denoland/deno_std/pull/820) as the linter allows.

> I added mod.ts for importing all fmt library. I tried to import but it couldn't find the mod.ts so I wanted to add, I hope Deno devs accept too, thank you.

### CODE REVIEW

**Comment by kitsonk** [comment]
We do not add copyright notices of other developers.  The two modules in here are fairly independent and do not require a `mod.ts`.  Respectfully closing without merge.

**Comment by handlederror** [comment]
Couldn't you just delete my copyright of mine? I don't really mind about that.

**Comment by kitsonk** [comment]
> The two modules in here are fairly independent and do not require a `mod.ts`.

**Comment by handlederror** [comment]
Oh, okay.

**Pull request closed without merging**
