### PR TITLE
fix(wasi): add output type 

### PR DESCRIPTION
**Pull request by behnammodi**

### CODE REVIEW

**Review by caspervonb — COMMENTED** [review]
Thanks for the pull request! but...
These things are inferred just fine, nothing being explicitly annotated here is public or even exported so my question is, why?

**Comment by behnammodi** [comment]
> Thanks for the pull request! but...
> These things are inferred just fine, nothing being explicitly annotated here is public or even exported so my question is, why?

Why not :) we specify output and input types everywhere of the codebase, so what is wrong with this?

**Comment by kt3k** [comment]
See this issue, for example, https://github.com/denoland/deno/issues/8832

We generally prefer avoiding unnecessary type annotations when typescript infers them correctly.

**Comment by behnammodi** [comment]
@kt3k I read your link, I convinced, so I'll close this PR if you agree

**Pull request closed without merging**
